In [1]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 1 — LOCATE AND VERIFY EXISTING STAGE-4 RESULTS
# ================================================================

from pathlib import Path
import pandas as pd
import json
import os

print("=" * 70)
print("T1.1 — ENDPOINT REDUNDANCY AUDIT")
print("Cell 1: Locate existing Stage-4 endpoint results")
print("=" * 70)

# ------------------------------------------------
# 1. Search common Kaggle locations
# ------------------------------------------------

candidates = []

search_roots = [
    Path("/kaggle/input"),
    Path("/kaggle/working"),
    Path("/kaggle/temp"),
]

for root in search_roots:
    if root.exists():
        for p in root.rglob("model_endpoints_final_checkpoint.csv"):
            candidates.append(p)

# Remove duplicates
candidates = sorted(set(candidates))

print(f"\nCandidate endpoint files found: {len(candidates)}")

for p in candidates:
    print("  ", p)

if not candidates:
    raise FileNotFoundError(
        "\nCould not find model_endpoints_final_checkpoint.csv.\n"
        "This means the Stage-4 results are not currently attached to this notebook.\n"
        "STOP HERE — do not run further cells yet."
    )

# ------------------------------------------------
# 2. Select the candidate
# ------------------------------------------------

if len(candidates) > 1:
    print("\nMultiple candidates found.")
    print("We will inspect them before selecting one.")
else:
    RESULTS_CSV = candidates[0]

# ------------------------------------------------
# 3. Load and inspect
# ------------------------------------------------

if len(candidates) == 1:

    df = pd.read_csv(RESULTS_CSV)

    print("\nSelected:")
    print(" ", RESULTS_CSV)

    print("\nShape:")
    print(" ", df.shape)

    print("\nColumns:")
    for c in df.columns:
        print("  -", c)

    print("\nFirst 5 rows:")
    display(df.head())

else:
    print("\nCandidate summaries:")

    for p in candidates:
        tmp = pd.read_csv(p)

        print("\n", p)
        print("  shape:", tmp.shape)
        print("  columns:", list(tmp.columns))

# ------------------------------------------------
# 4. Basic 30-model verification
# ------------------------------------------------

if len(candidates) == 1:

    assert len(df) == 30, (
        f"Expected exactly 30 model rows, found {len(df)}"
    )

    assert "model" in df.columns
    assert "rho" in df.columns
    assert "replicate" in df.columns

    print("\n✓ Exactly 30 model rows")

    # Expected rho levels
    expected_rho = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    observed_rho = sorted(df["rho"].unique().tolist())

    print("Observed rho levels:", observed_rho)

    assert observed_rho == expected_rho, (
        f"Unexpected rho levels: {observed_rho}"
    )

    print("✓ Six expected rho levels")

    # Five replicates per rho
    counts = df.groupby("rho")["replicate"].nunique()

    print("\nReplicates per rho:")
    print(counts)

    assert all(counts == 5), (
        "At least one rho level does not contain exactly 5 replicates."
    )

    print("✓ Five replicates at every rho")

    # ------------------------------------------------
    # 5. Missing-value audit
    # ------------------------------------------------

    print("\nMissing values:")

    missing = df.isna().sum()
    display(missing[missing > 0])

    if missing.sum() == 0:
        print("✓ No missing values")
    else:
        raise AssertionError(
            "Missing values detected. STOP before redundancy analysis."
        )

    # ------------------------------------------------
    # 6. Checkpoint
    # ------------------------------------------------

    if "checkpoint" in df.columns:

        checkpoints = df["checkpoint"].unique().tolist()

        print("\nCheckpoint values:", checkpoints)

        if len(checkpoints) == 1 and checkpoints[0] == "final":
            print("✓ Final checkpoint table confirmed")
        else:
            print(
                "⚠ Multiple checkpoint labels present — "
                "we will filter/inspect before analysis."
            )

    print("\n" + "=" * 70)
    print("CELL 1 PASSED")
    print("=" * 70)
    print("\nDo NOT run the next analysis yet.")

======================================================================
T1.1 — ENDPOINT REDUNDANCY AUDIT
Cell 1: Locate existing Stage-4 endpoint results
======================================================================

Candidate endpoint files found: 1
   /kaggle/input/notebooks/tejasseshadriiiii/isic-kaggle-analysis/results/model_endpoints_final_checkpoint.csv

Selected:
  /kaggle/input/notebooks/tejasseshadriiiii/isic-kaggle-analysis/results/model_endpoints_final_checkpoint.csv

Shape:
  (30, 32)

Columns:
  - model
  - rho
  - replicate
  - checkpoint
  - delta_z_hair
  - sd_z_clean
  - delta_z_norm
  - delta_p
  - flip_fraction
  - flip_benign_to_malignant
  - flip_malignant_to_benign
  - BA_clean
  - sens_clean
  - spec_clean
  - AUROC_clean
  - BA_reversed
  - sens_reversed
  - spec_reversed
  - AUROC_reversed
  - BA_matched
  - sens_matched
  - spec_matched
  - AUROC_matched
  - BA_neutral
  - sens_neutral
  - spec_neutral
  - AUROC_neutral
  - D
  - D_AUROC
  - BA_neutral_minus_reversed
  - xai_enrichment
  - xai_undefined_fraction

First 5 rows:

,model,rho,replicate,checkpoint,delta_z_hair,sd_z_clean,delta_z_norm,delta_p,flip_fraction,flip_benign_to_malignant,...,AUROC_matched,BA_neutral,sens_neutral,spec_neutral,AUROC_neutral,D,D_AUROC,BA_neutral_minus_reversed,xai_enrichment,xai_undefined_fraction
0,rho_0.6_rep_2,0.6,2,final,7.586214,8.618332,0.880242,0.357319,0.369192,0.368979,...,0.958036,0.745108,0.723002,0.767214,0.832705,0.148375,0.214307,0.146352,11.351470,0.0
1,rho_0.8_rep_3,0.8,3,final,10.074487,8.435467,1.194301,0.487600,0.500318,0.500318,...,0.964346,0.697920,0.656587,0.739252,0.797943,0.192415,0.313328,0.201736,14.225002,0.0
2,rho_1.0_rep_5,1.0,5,final,12.656182,6.959800,1.818469,0.585233,0.594950,0.594738,...,0.967088,0.655266,0.559395,0.751136,0.766981,0.198182,0.401225,0.263277,16.579338,0.0
3,rho_0.0_rep_5,0.0,5,final,1.563364,9.694409,0.161264,0.053061,0.064927,0.057501,...,0.916835,0.803635,0.739741,0.867529,0.892527,0.019748,0.028267,0.018520,6.742265,0.0
4,rho_1.0_rep_3,1.0,3,final,11.847715,6.447131,1.837672,0.586096,0.604923,0.604923,...,0.965935,0.643736,0.535637,0.751835,0.760911,0.198357,0.410223,0.268866,16.560037,0.0

✓ Exactly 30 model rows
Observed rho levels: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
✓ Six expected rho levels

Replicates per rho:
rho
0.0    5
0.2    5
0.4    5
0.6    5
0.8    5
1.0    5
Name: replicate, dtype: int64
✓ Five replicates at every rho

Missing values:

Series([], dtype: int64)

✓ No missing values

Checkpoint values: ['final']
✓ Final checkpoint table confirmed

======================================================================
CELL 1 PASSED
======================================================================

Do NOT run the next analysis yet.

In [2]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 2 — DEFINE ANALYSIS MATRIX
# ================================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("T1.1 — CELL 2: DEFINE ENDPOINT MATRIX")
print("=" * 70)

# ------------------------------------------------
# Endpoint groups
# ------------------------------------------------

# PRIMARY / direct counterfactual response
PRIMARY_ENDPOINTS = [
    "delta_z_hair",
]

# Same underlying counterfactual response represented
# on alternative scales
SCALE_TRANSFORM_ENDPOINTS = [
    "delta_z_norm",
    "delta_p",
    "flip_fraction",
]

# Directional behavioral consequence
BEHAVIOR_ENDPOINTS = [
    "D",
    "D_AUROC",
    "BA_neutral_minus_reversed",
]

# XAI evidence
XAI_ENDPOINTS = [
    "xai_enrichment",
]

ENDPOINTS = (
    PRIMARY_ENDPOINTS
    + SCALE_TRANSFORM_ENDPOINTS
    + BEHAVIOR_ENDPOINTS
    + XAI_ENDPOINTS
)

print("\nEndpoints selected for redundancy analysis:")

for i, col in enumerate(ENDPOINTS, 1):
    print(f"{i:2d}. {col}")

# ------------------------------------------------
# Verify all columns exist
# ------------------------------------------------

missing_cols = [c for c in ENDPOINTS if c not in df.columns]

assert not missing_cols, (
    f"Missing endpoint columns: {missing_cols}"
)

# ------------------------------------------------
# Create analysis matrix
# ------------------------------------------------

X = df[ENDPOINTS].copy()

# Attach model identifiers separately
META = df[["model", "rho", "replicate", "checkpoint"]].copy()

# ------------------------------------------------
# Check numerical validity
# ------------------------------------------------

assert X.shape == (30, len(ENDPOINTS))

assert np.isfinite(X.to_numpy()).all(), (
    "Non-finite endpoint values detected."
)

# ------------------------------------------------
# Print descriptive summary
# ------------------------------------------------

print("\nMatrix shape:")
print(" ", X.shape)

print("\nDescriptive statistics:")
display(
    X.describe().T[
        ["count", "mean", "std", "min", "max"]
    ]
)

# ------------------------------------------------
# Check whether each endpoint has variation
# ------------------------------------------------

print("\nUnique-value counts:")

unique_counts = X.nunique()

display(unique_counts.to_frame("n_unique"))

assert (unique_counts > 1).all(), (
    "At least one endpoint has no variation."
)

# ------------------------------------------------
# Save a clean copy for later cells
# ------------------------------------------------

T11_MATRIX = pd.concat([META, X], axis=1)

print("\n✓ Endpoint matrix constructed")
print("✓ All selected endpoints exist")
print("✓ All values finite")
print("✓ Every endpoint varies across the 30 models")

print("\n" + "=" * 70)
print("CELL 2 PASSED")
print("=" * 70)

======================================================================
T1.1 — CELL 2: DEFINE ENDPOINT MATRIX
======================================================================

Endpoints selected for redundancy analysis:
 1. delta_z_hair
 2. delta_z_norm
 3. delta_p
 4. flip_fraction
 5. D
 6. D_AUROC
 7. BA_neutral_minus_reversed
 8. xai_enrichment

Matrix shape:
  (30, 8)

Descriptive statistics:

                           count       mean       std       min        max
delta_z_hair                30.0   7.207105  3.458716  1.563364  12.842734
delta_z_norm                30.0   0.872326  0.531510  0.161264   1.841283
delta_p                     30.0   0.328091  0.175756  0.053061   0.607940
flip_fraction               30.0   0.338277  0.176510  0.064927   0.625504
D                           30.0   0.124123  0.061647  0.019748   0.215484
D_AUROC                     30.0   0.205657  0.125574  0.028267   0.419234
BA_neutral_minus_reversed   30.0   0.138548  0.078839  0.018520   0.276414
xai_enrichment              30.0  11.936340  3.251731  6.742265  19.017664

Unique-value counts:

                           n_unique
delta_z_hair                     30
delta_z_norm                     30
delta_p                          30
flip_fraction                    30
D                                30
D_AUROC                          30
BA_neutral_minus_reversed        30
xai_enrichment                   30

✓ Endpoint matrix constructed
✓ All selected endpoints exist
✓ All values finite
✓ Every endpoint varies across the 30 models

======================================================================
CELL 2 PASSED
======================================================================

In [3]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 3 — PEARSON + SPEARMAN CORRELATION AUDIT
# ================================================================

from scipy.stats import pearsonr, spearmanr
import numpy as np
import pandas as pd

print("=" * 70)
print("T1.1 — CELL 3: ENDPOINT CORRELATION AUDIT")
print("=" * 70)

# ------------------------------------------------
# 1. Pearson correlation
# ------------------------------------------------

pearson_r = X.corr(method="pearson")

# ------------------------------------------------
# 2. Spearman rank correlation
# ------------------------------------------------

spearman_r = X.corr(method="spearman")

print("\nPEARSON CORRELATION MATRIX")
print("-" * 70)
display(pearson_r.round(4))

print("\nSPEARMAN CORRELATION MATRIX")
print("-" * 70)
display(spearman_r.round(4))

# ------------------------------------------------
# 3. Convert matrices to pairwise long format
# ------------------------------------------------

pairs = []

for i, a in enumerate(ENDPOINTS):
    for j, b in enumerate(ENDPOINTS):

        if j <= i:
            continue

        x = X[a].to_numpy()
        y = X[b].to_numpy()

        r_p, p_p = pearsonr(x, y)
        r_s, p_s = spearmanr(x, y)

        pairs.append({
            "endpoint_A": a,
            "endpoint_B": b,
            "pearson_r": r_p,
            "pearson_abs": abs(r_p),
            "spearman_r": r_s,
            "spearman_abs": abs(r_s),
            "pearson_p": p_p,
            "spearman_p": p_s,
        })

pairwise_corr = (
    pd.DataFrame(pairs)
    .sort_values(
        ["spearman_abs", "pearson_abs"],
        ascending=False
    )
    .reset_index(drop=True)
)

print("\nPAIRWISE CORRELATIONS — SORTED BY |SPEARMAN|")
print("-" * 70)

display(
    pairwise_corr.round(4)
)

# ------------------------------------------------
# 4. Identify very-highly correlated pairs
# ------------------------------------------------

HIGH_THRESHOLD = 0.90
MODERATE_THRESHOLD = 0.70

high = pairwise_corr[
    pairwise_corr["spearman_abs"] >= HIGH_THRESHOLD
]

moderate = pairwise_corr[
    (pairwise_corr["spearman_abs"] >= MODERATE_THRESHOLD)
    &
    (pairwise_corr["spearman_abs"] < HIGH_THRESHOLD)
]

print("\nHIGH REDUNDANCY PAIRS: |Spearman| >= 0.90")
print("-" * 70)

if len(high):
    display(high.round(4))
else:
    print("None")

print("\nMODERATE/HIGH ASSOCIATION PAIRS: 0.70 <= |Spearman| < 0.90")
print("-" * 70)

if len(moderate):
    display(moderate.round(4))
else:
    print("None")

# ------------------------------------------------
# 5. Direct audit of primary endpoint
# ------------------------------------------------

primary_corr = pairwise_corr[
    (pairwise_corr["endpoint_A"] == "delta_z_hair")
    |
    (pairwise_corr["endpoint_B"] == "delta_z_hair")
].copy()

print("\nRELATIONSHIP OF EVERY ENDPOINT WITH PRIMARY Δz_hair")
print("-" * 70)

display(primary_corr.round(4))

# ------------------------------------------------
# 6. Save outputs
# ------------------------------------------------

pairwise_corr.to_csv(
    "T1_1_pairwise_endpoint_correlations.csv",
    index=False
)

pearson_r.to_csv(
    "T1_1_pearson_matrix.csv"
)

spearman_r.to_csv(
    "T1_1_spearman_matrix.csv"
)

print("\n✓ Pearson matrix calculated")
print("✓ Spearman matrix calculated")
print("✓ Pairwise correlation table created")
print("✓ Primary-endpoint relationships extracted")
print("✓ Results saved")

print("\n" + "=" * 70)
print("CELL 3 COMPLETE")
print("=" * 70)

print(
    "\nIMPORTANT: Do not interpret the scientific redundancy "
    "conclusion yet. We still need the rank-equivalence and "
    "mechanistic audits."
)

======================================================================
T1.1 — CELL 3: ENDPOINT CORRELATION AUDIT
======================================================================

PEARSON CORRELATION MATRIX
----------------------------------------------------------------------

,delta_z_hair,delta_z_norm,delta_p,flip_fraction,D,D_AUROC,BA_neutral_minus_reversed,xai_enrichment
delta_z_hair,1.0000,0.9750,0.9961,0.9946,0.9881,0.9893,0.9905,0.9835
delta_z_norm,0.9750,1.0000,0.9811,0.9827,0.9473,0.9920,0.9902,0.9827
delta_p,0.9961,0.9811,1.0000,0.9998,0.9900,0.9956,0.9967,0.9825
flip_fraction,0.9946,0.9827,0.9998,1.0000,0.9883,0.9967,0.9976,0.9824
D,0.9881,0.9473,0.9900,0.9883,1.0000,0.9739,0.9778,0.9613
D_AUROC,0.9893,0.9920,0.9956,0.9967,0.9739,1.0000,0.9981,0.9844
BA_neutral_minus_reversed,0.9905,0.9902,0.9967,0.9976,0.9778,0.9981,1.0000,0.9834
xai_enrichment,0.9835,0.9827,0.9825,0.9824,0.9613,0.9844,0.9834,1.0000

SPEARMAN CORRELATION MATRIX
----------------------------------------------------------------------

,delta_z_hair,delta_z_norm,delta_p,flip_fraction,D,D_AUROC,BA_neutral_minus_reversed,xai_enrichment
delta_z_hair,1.0000,0.9849,0.9840,0.9782,0.9791,0.9835,0.9720,0.9849
delta_z_norm,0.9849,1.0000,0.9893,0.9884,0.9831,0.9915,0.9826,0.9764
delta_p,0.9840,0.9893,1.0000,0.9973,0.9915,0.9956,0.9898,0.9809
flip_fraction,0.9782,0.9884,0.9973,1.0000,0.9929,0.9933,0.9924,0.9804
D,0.9791,0.9831,0.9915,0.9929,1.0000,0.9893,0.9844,0.9778
D_AUROC,0.9835,0.9915,0.9956,0.9933,0.9893,1.0000,0.9875,0.9858
BA_neutral_minus_reversed,0.9720,0.9826,0.9898,0.9924,0.9844,0.9875,1.0000,0.9782
xai_enrichment,0.9849,0.9764,0.9809,0.9804,0.9778,0.9858,0.9782,1.0000

PAIRWISE CORRELATIONS — SORTED BY |SPEARMAN|
----------------------------------------------------------------------

,endpoint_A,endpoint_B,pearson_r,pearson_abs,spearman_r,spearman_abs,pearson_p,spearman_p
0,delta_p,flip_fraction,0.9998,0.9998,0.9973,0.9973,0.0,0.0
1,delta_p,D_AUROC,0.9956,0.9956,0.9956,0.9956,0.0,0.0
2,flip_fraction,D_AUROC,0.9967,0.9967,0.9933,0.9933,0.0,0.0
3,flip_fraction,D,0.9883,0.9883,0.9929,0.9929,0.0,0.0
4,flip_fraction,BA_neutral_minus_reversed,0.9976,0.9976,0.9924,0.9924,0.0,0.0
5,delta_z_norm,D_AUROC,0.9920,0.9920,0.9915,0.9915,0.0,0.0
6,delta_p,D,0.9900,0.9900,0.9915,0.9915,0.0,0.0
7,delta_p,BA_neutral_minus_reversed,0.9967,0.9967,0.9898,0.9898,0.0,0.0
8,delta_z_norm,delta_p,0.9811,0.9811,0.9893,0.9893,0.0,0.0
9,D,D_AUROC,0.9739,0.9739,0.9893,0.9893,0.0,0.0
10,delta_z_norm,flip_fraction,0.9827,0.9827,0.9884,0.9884,0.0,0.0
11,D_AUROC,BA_neutral_minus_reversed,0.9981,0.9981,0.9875,0.9875,0.0,0.0
12,D_AUROC,xai_enrichment,0.9844,0.9844,0.9858,0.9858,0.0,0.0
13,delta_z_hair,xai_enrichment,0.9835,0.9835,0.9849,0.9849,0.0,0.0
14,delta_z_hair,delta_z_norm,0.9750,0.9750,0.9849,0.9849,0.0,0.0
15,D,BA_neutral_minus_reversed,0.9778,0.9778,0.9844,0.9844,0.0,0.0
16,delta_z_hair,delta_p,0.9961,0.9961,0.9840,0.9840,0.0,0.0
17,delta_z_hair,D_AUROC,0.9893,0.9893,0.9835,0.9835,0.0,0.0
18,delta_z_norm,D,0.9473,0.9473,0.9831,0.9831,0.0,0.0
19,delta_z_norm,BA_neutral_minus_reversed,0.9902,0.9902,0.9826,0.9826,0.0,0.0
20,delta_p,xai_enrichment,0.9825,0.9825,0.9809,0.9809,0.0,0.0
21,flip_fraction,xai_enrichment,0.9824,0.9824,0.9804,0.9804,0.0,0.0
22,delta_z_hair,D,0.9881,0.9881,0.9791,0.9791,0.0,0.0
23,delta_z_hair,flip_fraction,0.9946,0.9946,0.9782,0.9782,0.0,0.0
24,BA_neutral_minus_reversed,xai_enrichment,0.9834,0.9834,0.9782,0.9782,0.0,0.0
25,D,xai_enrichment,0.9613,0.9613,0.9778,0.9778,0.0,0.0
26,delta_z_norm,xai_enrichment,0.9827,0.9827,0.9764,0.9764,0.0,0.0
27,delta_z_hair,BA_neutral_minus_reversed,0.9905,0.9905,0.9720,0.9720,0.0,0.0

HIGH REDUNDANCY PAIRS: |Spearman| >= 0.90
----------------------------------------------------------------------

,endpoint_A,endpoint_B,pearson_r,pearson_abs,spearman_r,spearman_abs,pearson_p,spearman_p
0,delta_p,flip_fraction,0.9998,0.9998,0.9973,0.9973,0.0,0.0
1,delta_p,D_AUROC,0.9956,0.9956,0.9956,0.9956,0.0,0.0
2,flip_fraction,D_AUROC,0.9967,0.9967,0.9933,0.9933,0.0,0.0
3,flip_fraction,D,0.9883,0.9883,0.9929,0.9929,0.0,0.0
4,flip_fraction,BA_neutral_minus_reversed,0.9976,0.9976,0.9924,0.9924,0.0,0.0
5,delta_z_norm,D_AUROC,0.9920,0.9920,0.9915,0.9915,0.0,0.0
6,delta_p,D,0.9900,0.9900,0.9915,0.9915,0.0,0.0
7,delta_p,BA_neutral_minus_reversed,0.9967,0.9967,0.9898,0.9898,0.0,0.0
8,delta_z_norm,delta_p,0.9811,0.9811,0.9893,0.9893,0.0,0.0
9,D,D_AUROC,0.9739,0.9739,0.9893,0.9893,0.0,0.0
10,delta_z_norm,flip_fraction,0.9827,0.9827,0.9884,0.9884,0.0,0.0
11,D_AUROC,BA_neutral_minus_reversed,0.9981,0.9981,0.9875,0.9875,0.0,0.0
12,D_AUROC,xai_enrichment,0.9844,0.9844,0.9858,0.9858,0.0,0.0
13,delta_z_hair,xai_enrichment,0.9835,0.9835,0.9849,0.9849,0.0,0.0
14,delta_z_hair,delta_z_norm,0.9750,0.9750,0.9849,0.9849,0.0,0.0
15,D,BA_neutral_minus_reversed,0.9778,0.9778,0.9844,0.9844,0.0,0.0
16,delta_z_hair,delta_p,0.9961,0.9961,0.9840,0.9840,0.0,0.0
17,delta_z_hair,D_AUROC,0.9893,0.9893,0.9835,0.9835,0.0,0.0
18,delta_z_norm,D,0.9473,0.9473,0.9831,0.9831,0.0,0.0
19,delta_z_norm,BA_neutral_minus_reversed,0.9902,0.9902,0.9826,0.9826,0.0,0.0
20,delta_p,xai_enrichment,0.9825,0.9825,0.9809,0.9809,0.0,0.0
21,flip_fraction,xai_enrichment,0.9824,0.9824,0.9804,0.9804,0.0,0.0
22,delta_z_hair,D,0.9881,0.9881,0.9791,0.9791,0.0,0.0
23,delta_z_hair,flip_fraction,0.9946,0.9946,0.9782,0.9782,0.0,0.0
24,BA_neutral_minus_reversed,xai_enrichment,0.9834,0.9834,0.9782,0.9782,0.0,0.0
25,D,xai_enrichment,0.9613,0.9613,0.9778,0.9778,0.0,0.0
26,delta_z_norm,xai_enrichment,0.9827,0.9827,0.9764,0.9764,0.0,0.0
27,delta_z_hair,BA_neutral_minus_reversed,0.9905,0.9905,0.9720,0.9720,0.0,0.0

MODERATE/HIGH ASSOCIATION PAIRS: 0.70 <= |Spearman| < 0.90
----------------------------------------------------------------------
None

RELATIONSHIP OF EVERY ENDPOINT WITH PRIMARY Δz_hair
----------------------------------------------------------------------

,endpoint_A,endpoint_B,pearson_r,pearson_abs,spearman_r,spearman_abs,pearson_p,spearman_p
13,delta_z_hair,xai_enrichment,0.9835,0.9835,0.9849,0.9849,0.0,0.0
14,delta_z_hair,delta_z_norm,0.9750,0.9750,0.9849,0.9849,0.0,0.0
16,delta_z_hair,delta_p,0.9961,0.9961,0.9840,0.9840,0.0,0.0
17,delta_z_hair,D_AUROC,0.9893,0.9893,0.9835,0.9835,0.0,0.0
22,delta_z_hair,D,0.9881,0.9881,0.9791,0.9791,0.0,0.0
23,delta_z_hair,flip_fraction,0.9946,0.9946,0.9782,0.9782,0.0,0.0
27,delta_z_hair,BA_neutral_minus_reversed,0.9905,0.9905,0.9720,0.9720,0.0,0.0

✓ Pearson matrix calculated
✓ Spearman matrix calculated
✓ Pairwise correlation table created
✓ Primary-endpoint relationships extracted
✓ Results saved

======================================================================
CELL 3 COMPLETE
======================================================================

IMPORTANT: Do not interpret the scientific redundancy conclusion yet. We still need the rank-equivalence and mechanistic audits.

In [4]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 4 — WITHIN-rho CROSS-ENDPOINT CORRELATIONS
# ================================================================

from scipy.stats import pearsonr, spearmanr
import numpy as np
import pandas as pd

print("=" * 70)
print("T1.1 — CELL 4: WITHIN-rho CROSS-ENDPOINT AUDIT")
print("=" * 70)

# ------------------------------------------------
# Endpoint pairs of primary scientific interest
# ------------------------------------------------

MECHANISTIC_PAIRS = [
    ("delta_z_hair", "delta_z_norm"),
    ("delta_z_hair", "delta_p"),
    ("delta_z_hair", "flip_fraction"),
    ("delta_z_hair", "D"),
    ("delta_z_hair", "D_AUROC"),
    ("delta_z_hair", "BA_neutral_minus_reversed"),
    ("delta_z_hair", "xai_enrichment"),
    ("D", "D_AUROC"),
    ("D", "BA_neutral_minus_reversed"),
    ("D_AUROC", "xai_enrichment"),
]

# ------------------------------------------------
# Calculate correlations separately within each rho
# ------------------------------------------------

rows = []

for rho, g in df.groupby("rho", sort=True):

    for a, b in MECHANISTIC_PAIRS:

        x = g[a].to_numpy()
        y = g[b].to_numpy()

        # n = 5 at each rho
        r_p, p_p = pearsonr(x, y)
        r_s, p_s = spearmanr(x, y)

        rows.append({
            "rho": rho,
            "endpoint_A": a,
            "endpoint_B": b,
            "pearson_r": r_p,
            "spearman_r": r_s,
            "pearson_p": p_p,
            "spearman_p": p_s,
        })

within_rho = pd.DataFrame(rows)

print("\nWITHIN-rho CORRELATIONS")
print("-" * 70)

display(
    within_rho.round(4)
)

# ------------------------------------------------
# Focus on primary Δz relationships
# ------------------------------------------------

primary_within = within_rho[
    within_rho["endpoint_A"] == "delta_z_hair"
].copy()

print("\nWITHIN-rho RELATIONSHIPS WITH PRIMARY Δz_hair")
print("-" * 70)

display(
    primary_within.round(4)
)

# ------------------------------------------------
# Summarize consistency across rho
# ------------------------------------------------

summary_rows = []

for (a, b), g in within_rho.groupby(
    ["endpoint_A", "endpoint_B"]
):

    summary_rows.append({
        "endpoint_A": a,
        "endpoint_B": b,
        "mean_within_rho_spearman":
            g["spearman_r"].mean(),
        "median_within_rho_spearman":
            g["spearman_r"].median(),
        "min_within_rho_spearman":
            g["spearman_r"].min(),
        "max_within_rho_spearman":
            g["spearman_r"].max(),
        "mean_within_rho_pearson":
            g["pearson_r"].mean(),
        "median_within_rho_pearson":
            g["pearson_r"].median(),
    })

within_summary = pd.DataFrame(summary_rows)

print("\nSUMMARY ACROSS THE SIX rho LEVELS")
print("-" * 70)

display(
    within_summary.round(4)
)

# ------------------------------------------------
# Save
# ------------------------------------------------

within_rho.to_csv(
    "T1_1_within_rho_correlations.csv",
    index=False
)

within_summary.to_csv(
    "T1_1_within_rho_correlation_summary.csv",
    index=False
)

print("\n✓ Within-rho correlations calculated")
print("✓ Six rho levels evaluated separately")
print("✓ Primary Δz relationships extracted")
print("✓ Summary table saved")

print("\n" + "=" * 70)
print("CELL 4 COMPLETE")
print("=" * 70)

======================================================================
T1.1 — CELL 4: WITHIN-rho CROSS-ENDPOINT AUDIT
======================================================================

WITHIN-rho CORRELATIONS
----------------------------------------------------------------------

,rho,endpoint_A,endpoint_B,pearson_r,spearman_r,pearson_p,spearman_p
0,0.0,delta_z_hair,delta_z_norm,0.9562,0.9,0.0109,0.0374
1,0.0,delta_z_hair,delta_p,0.9423,0.9,0.0165,0.0374
2,0.0,delta_z_hair,flip_fraction,0.9261,0.9,0.0239,0.0374
3,0.0,delta_z_hair,D,0.6855,0.7,0.2014,0.1881
4,0.0,delta_z_hair,D_AUROC,0.9919,1.0,0.0009,0.0000
5,0.0,delta_z_hair,BA_neutral_minus_reversed,0.7675,0.7,0.1297,0.1881
6,0.0,delta_z_hair,xai_enrichment,0.8439,0.8,0.0723,0.1041
7,0.0,D,D_AUROC,0.6109,0.7,0.2737,0.1881
8,0.0,D,BA_neutral_minus_reversed,0.9725,1.0,0.0054,0.0000
9,0.0,D_AUROC,xai_enrichment,0.8070,0.8,0.0988,0.1041
10,0.2,delta_z_hair,delta_z_norm,0.7919,0.6,0.1103,0.2848
11,0.2,delta_z_hair,delta_p,0.0007,-0.1,0.9991,0.8729
12,0.2,delta_z_hair,flip_fraction,0.1729,-0.1,0.7810,0.8729
13,0.2,delta_z_hair,D,-0.0193,-0.1,0.9754,0.8729
14,0.2,delta_z_hair,D_AUROC,0.3342,0.3,0.5826,0.6238
15,0.2,delta_z_hair,BA_neutral_minus_reversed,0.2041,-0.1,0.7420,0.8729
16,0.2,delta_z_hair,xai_enrichment,0.5310,0.3,0.3572,0.6238
17,0.2,D,D_AUROC,0.8722,0.9,0.0538,0.0374
18,0.2,D,BA_neutral_minus_reversed,0.9659,1.0,0.0075,0.0000
19,0.2,D_AUROC,xai_enrichment,0.2716,0.3,0.6585,0.6238
20,0.4,delta_z_hair,delta_z_norm,0.1669,0.3,0.7885,0.6238
21,0.4,delta_z_hair,delta_p,-0.3726,0.1,0.5368,0.8729
22,0.4,delta_z_hair,flip_fraction,-0.4834,-0.5,0.4094,0.3910
23,0.4,delta_z_hair,D,-0.5913,-0.4,0.2936,0.5046
24,0.4,delta_z_hair,D_AUROC,-0.1185,0.1,0.8495,0.8729
25,0.4,delta_z_hair,BA_neutral_minus_reversed,-0.7935,-0.7,0.1091,0.1881
26,0.4,delta_z_hair,xai_enrichment,-0.1543,-0.1,0.8043,0.8729
27,0.4,D,D_AUROC,0.8348,0.7,0.0786,0.1881
28,0.4,D,BA_neutral_minus_reversed,0.7511,0.6,0.1434,0.2848
29,0.4,D_AUROC,xai_enrichment,0.7528,0.7,0.1420,0.1881
30,0.6,delta_z_hair,delta_z_norm,0.0705,-0.1,0.9103,0.8729
31,0.6,delta_z_hair,delta_p,0.3491,0.3,0.5647,0.6238
32,0.6,delta_z_hair,flip_fraction,0.1318,0.1,0.8327,0.8729
33,0.6,delta_z_hair,D,0.5780,0.4,0.3074,0.5046
34,0.6,delta_z_hair,D_AUROC,-0.0599,-0.2,0.9238,0.7471
35,0.6,delta_z_hair,BA_neutral_minus_reversed,0.0184,-0.1,0.9765,0.8729
36,0.6,delta_z_hair,xai_enrichment,0.6445,0.7,0.2404,0.1881
37,0.6,D,D_AUROC,-0.2272,-0.1,0.7132,0.8729
38,0.6,D,BA_neutral_minus_reversed,0.1562,-0.2,0.8019,0.7471
39,0.6,D_AUROC,xai_enrichment,0.1726,0.2,0.7813,0.7471
40,0.8,delta_z_hair,delta_z_norm,0.5893,0.6,0.2957,0.2848
41,0.8,delta_z_hair,delta_p,0.7424,0.9,0.1508,0.0374
42,0.8,delta_z_hair,flip_fraction,0.6193,0.6,0.2653,0.2848
43,0.8,delta_z_hair,D,0.5567,0.5,0.3298,0.3910
44,0.8,delta_z_hair,D_AUROC,0.7672,0.8,0.1300,0.1041
45,0.8,delta_z_hair,BA_neutral_minus_reversed,0.1725,0.1,0.7814,0.8729
46,0.8,delta_z_hair,xai_enrichment,0.4295,0.6,0.4705,0.2848
47,0.8,D,D_AUROC,0.4836,0.7,0.4092,0.1881
48,0.8,D,BA_neutral_minus_reversed,0.3689,-0.1,0.5412,0.8729
49,0.8,D_AUROC,xai_enrichment,0.8790,0.6,0.0496,0.2848
50,1.0,delta_z_hair,delta_z_norm,0.3267,0.3,0.5915,0.6238
51,1.0,delta_z_hair,delta_p,0.1905,0.3,0.7589,0.6238
52,1.0,delta_z_hair,flip_fraction,-0.1669,0.1,0.7884,0.8729
53,1.0,delta_z_hair,D,0.0208,0.2,0.9735,0.7471
54,1.0,delta_z_hair,D_AUROC,0.0711,0.3,0.9096,0.6238
55,1.0,delta_z_hair,BA_neutral_minus_reversed,-0.2760,-0.2,0.6531,0.7471
56,1.0,delta_z_hair,xai_enrichment,0.6581,0.7,0.2272,0.1881
57,1.0,D,D_AUROC,0.4624,0.7,0.4330,0.1881
58,1.0,D,BA_neutral_minus_reversed,0.3465,0.2,0.5678,0.7471
59,1.0,D_AUROC,xai_enrichment,0.3539,0.5,0.5590,0.3910

WITHIN-rho RELATIONSHIPS WITH PRIMARY Δz_hair
----------------------------------------------------------------------

,rho,endpoint_A,endpoint_B,pearson_r,spearman_r,pearson_p,spearman_p
0,0.0,delta_z_hair,delta_z_norm,0.9562,0.9,0.0109,0.0374
1,0.0,delta_z_hair,delta_p,0.9423,0.9,0.0165,0.0374
2,0.0,delta_z_hair,flip_fraction,0.9261,0.9,0.0239,0.0374
3,0.0,delta_z_hair,D,0.6855,0.7,0.2014,0.1881
4,0.0,delta_z_hair,D_AUROC,0.9919,1.0,0.0009,0.0000
5,0.0,delta_z_hair,BA_neutral_minus_reversed,0.7675,0.7,0.1297,0.1881
6,0.0,delta_z_hair,xai_enrichment,0.8439,0.8,0.0723,0.1041
10,0.2,delta_z_hair,delta_z_norm,0.7919,0.6,0.1103,0.2848
11,0.2,delta_z_hair,delta_p,0.0007,-0.1,0.9991,0.8729
12,0.2,delta_z_hair,flip_fraction,0.1729,-0.1,0.7810,0.8729
13,0.2,delta_z_hair,D,-0.0193,-0.1,0.9754,0.8729
14,0.2,delta_z_hair,D_AUROC,0.3342,0.3,0.5826,0.6238
15,0.2,delta_z_hair,BA_neutral_minus_reversed,0.2041,-0.1,0.7420,0.8729
16,0.2,delta_z_hair,xai_enrichment,0.5310,0.3,0.3572,0.6238
20,0.4,delta_z_hair,delta_z_norm,0.1669,0.3,0.7885,0.6238
21,0.4,delta_z_hair,delta_p,-0.3726,0.1,0.5368,0.8729
22,0.4,delta_z_hair,flip_fraction,-0.4834,-0.5,0.4094,0.3910
23,0.4,delta_z_hair,D,-0.5913,-0.4,0.2936,0.5046
24,0.4,delta_z_hair,D_AUROC,-0.1185,0.1,0.8495,0.8729
25,0.4,delta_z_hair,BA_neutral_minus_reversed,-0.7935,-0.7,0.1091,0.1881
26,0.4,delta_z_hair,xai_enrichment,-0.1543,-0.1,0.8043,0.8729
30,0.6,delta_z_hair,delta_z_norm,0.0705,-0.1,0.9103,0.8729
31,0.6,delta_z_hair,delta_p,0.3491,0.3,0.5647,0.6238
32,0.6,delta_z_hair,flip_fraction,0.1318,0.1,0.8327,0.8729
33,0.6,delta_z_hair,D,0.5780,0.4,0.3074,0.5046
34,0.6,delta_z_hair,D_AUROC,-0.0599,-0.2,0.9238,0.7471
35,0.6,delta_z_hair,BA_neutral_minus_reversed,0.0184,-0.1,0.9765,0.8729
36,0.6,delta_z_hair,xai_enrichment,0.6445,0.7,0.2404,0.1881
40,0.8,delta_z_hair,delta_z_norm,0.5893,0.6,0.2957,0.2848
41,0.8,delta_z_hair,delta_p,0.7424,0.9,0.1508,0.0374
42,0.8,delta_z_hair,flip_fraction,0.6193,0.6,0.2653,0.2848
43,0.8,delta_z_hair,D,0.5567,0.5,0.3298,0.3910
44,0.8,delta_z_hair,D_AUROC,0.7672,0.8,0.1300,0.1041
45,0.8,delta_z_hair,BA_neutral_minus_reversed,0.1725,0.1,0.7814,0.8729
46,0.8,delta_z_hair,xai_enrichment,0.4295,0.6,0.4705,0.2848
50,1.0,delta_z_hair,delta_z_norm,0.3267,0.3,0.5915,0.6238
51,1.0,delta_z_hair,delta_p,0.1905,0.3,0.7589,0.6238
52,1.0,delta_z_hair,flip_fraction,-0.1669,0.1,0.7884,0.8729
53,1.0,delta_z_hair,D,0.0208,0.2,0.9735,0.7471
54,1.0,delta_z_hair,D_AUROC,0.0711,0.3,0.9096,0.6238
55,1.0,delta_z_hair,BA_neutral_minus_reversed,-0.2760,-0.2,0.6531,0.7471
56,1.0,delta_z_hair,xai_enrichment,0.6581,0.7,0.2272,0.1881

SUMMARY ACROSS THE SIX rho LEVELS
----------------------------------------------------------------------

,endpoint_A,endpoint_B,mean_within_rho_spearman,median_within_rho_spearman,min_within_rho_spearman,max_within_rho_spearman,mean_within_rho_pearson,median_within_rho_pearson
0,D,BA_neutral_minus_reversed,0.4167,0.40,-0.2,1.0,0.5935,0.5600
1,D,D_AUROC,0.6000,0.70,-0.1,0.9,0.5061,0.5472
2,D_AUROC,xai_enrichment,0.5167,0.55,0.2,0.8,0.5395,0.5533
3,delta_z_hair,BA_neutral_minus_reversed,-0.0500,-0.10,-0.7,0.7,0.0155,0.0955
4,delta_z_hair,D,0.2167,0.30,-0.4,0.7,0.2051,0.2887
5,delta_z_hair,D_AUROC,0.3833,0.30,-0.2,1.0,0.3310,0.2026
6,delta_z_hair,delta_p,0.4000,0.30,-0.1,0.9,0.3087,0.2698
7,delta_z_hair,delta_z_norm,0.4333,0.45,-0.1,0.9,0.4836,0.4580
8,delta_z_hair,flip_fraction,0.1833,0.10,-0.5,0.9,0.1999,0.1523
9,delta_z_hair,xai_enrichment,0.5000,0.65,-0.1,0.8,0.4921,0.5878

✓ Within-rho correlations calculated
✓ Six rho levels evaluated separately
✓ Primary Δz relationships extracted
✓ Summary table saved

======================================================================
CELL 4 COMPLETE
======================================================================

In [5]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 5 — ASSOCIATIONS AFTER REMOVING THE COMMON rho EFFECT
# ================================================================

import numpy as np
import pandas as pd
from scipy.stats import spearmanr, pearsonr
from sklearn.linear_model import LinearRegression

print("=" * 70)
print("T1.1 — CELL 5: rho-ADJUSTED ENDPOINT ASSOCIATIONS")
print("=" * 70)

# ------------------------------------------------
# Helper: rank-transform a vector
# ------------------------------------------------

def rank_vector(x):
    return pd.Series(x).rank(method="average").to_numpy()


# ------------------------------------------------
# Residualize ranked endpoint against ranked rho
# ------------------------------------------------

rho_rank = rank_vector(df["rho"].to_numpy()).reshape(-1, 1)

rank_residuals = {}

for col in ENDPOINTS:

    y_rank = rank_vector(df[col].to_numpy())

    model = LinearRegression()
    model.fit(rho_rank, y_rank)

    predicted = model.predict(rho_rank)

    rank_residuals[col] = y_rank - predicted


R = pd.DataFrame(rank_residuals)


# ------------------------------------------------
# Partial Spearman correlation matrix
# ------------------------------------------------

partial_rows = []

for i, a in enumerate(ENDPOINTS):

    for j, b in enumerate(ENDPOINTS):

        if j <= i:
            continue

        r, p = pearsonr(
            R[a].to_numpy(),
            R[b].to_numpy()
        )

        partial_rows.append({
            "endpoint_A": a,
            "endpoint_B": b,
            "partial_spearman_rho_controlled_for_rho": r,
            "p_value": p,
        })

partial_df = (
    pd.DataFrame(partial_rows)
    .sort_values(
        "partial_spearman_rho_controlled_for_rho",
        key=lambda s: s.abs(),
        ascending=False
    )
    .reset_index(drop=True)
)


# ------------------------------------------------
# Display
# ------------------------------------------------

print("\nPARTIAL SPEARMAN CORRELATIONS")
print("(ρ effect removed using rank residualization)")
print("-" * 70)

display(
    partial_df.round(4)
)


# ------------------------------------------------
# Primary endpoint relationships
# ------------------------------------------------

primary_partial = partial_df[
    (partial_df["endpoint_A"] == "delta_z_hair")
    |
    (partial_df["endpoint_B"] == "delta_z_hair")
].copy()

print("\nPRIMARY Δz_hair — rho-ADJUSTED ASSOCIATIONS")
print("-" * 70)

display(
    primary_partial.round(4)
)


# ------------------------------------------------
# Flag high residual associations
# ------------------------------------------------

HIGH_PARTIAL = 0.70
MODERATE_PARTIAL = 0.40

high_partial = partial_df[
    partial_df[
        "partial_spearman_rho_controlled_for_rho"
    ].abs() >= HIGH_PARTIAL
]

moderate_partial = partial_df[
    (
        partial_df[
            "partial_spearman_rho_controlled_for_rho"
        ].abs() >= MODERATE_PARTIAL
    )
    &
    (
        partial_df[
            "partial_spearman_rho_controlled_for_rho"
        ].abs() < HIGH_PARTIAL
    )
]

print(
    "\nHIGH rho-ADJUSTED ASSOCIATIONS "
    f"(|partial Spearman| >= {HIGH_PARTIAL})"
)
print("-" * 70)

if len(high_partial):
    display(high_partial.round(4))
else:
    print("None")


print(
    "\nMODERATE rho-ADJUSTED ASSOCIATIONS "
    f"({MODERATE_PARTIAL} <= |partial Spearman| < {HIGH_PARTIAL})"
)
print("-" * 70)

if len(moderate_partial):
    display(moderate_partial.round(4))
else:
    print("None")


# ------------------------------------------------
# Save
# ------------------------------------------------

partial_df.to_csv(
    "T1_1_partial_spearman_controlled_rho.csv",
    index=False
)

R.to_csv(
    "T1_1_rank_residuals_after_rho.csv",
    index=False
)

print("\n✓ Rank residualization completed")
print("✓ Partial Spearman associations calculated")
print("✓ Primary Δz relationships extracted")
print("✓ Results saved")

print("\n" + "=" * 70)
print("CELL 5 COMPLETE")
print("=" * 70)

print(
    "\nInterpretation is intentionally deferred until "
    "the rank-equivalence and PCA audits are complete."
)

======================================================================
T1.1 — CELL 5: rho-ADJUSTED ENDPOINT ASSOCIATIONS
======================================================================

PARTIAL SPEARMAN CORRELATIONS
(ρ effect removed using rank residualization)
----------------------------------------------------------------------

,endpoint_A,endpoint_B,partial_spearman_rho_controlled_for_rho,p_value
0,delta_p,flip_fraction,0.9000,0.0000
1,delta_p,D_AUROC,0.8333,0.0000
2,flip_fraction,D_AUROC,0.7500,0.0000
3,flip_fraction,D,0.7333,0.0000
4,flip_fraction,BA_neutral_minus_reversed,0.7167,0.0000
5,delta_z_norm,D_AUROC,0.6833,0.0000
6,delta_p,D,0.6833,0.0000
7,delta_p,BA_neutral_minus_reversed,0.6167,0.0003
8,delta_z_norm,delta_p,0.6000,0.0005
9,D,D_AUROC,0.6000,0.0005
10,delta_z_norm,flip_fraction,0.5667,0.0011
11,D_AUROC,BA_neutral_minus_reversed,0.5333,0.0024
12,D_AUROC,xai_enrichment,0.5092,0.0041
13,delta_z_hair,xai_enrichment,0.4784,0.0075
14,delta_z_hair,delta_z_norm,0.4333,0.0168
15,D,BA_neutral_minus_reversed,0.4167,0.0220
16,delta_z_hair,delta_p,0.4000,0.0285
17,delta_z_hair,D_AUROC,0.3833,0.0365
18,delta_z_norm,D,0.3667,0.0463
19,delta_z_norm,BA_neutral_minus_reversed,0.3500,0.0580
20,delta_p,xai_enrichment,0.3395,0.0664
21,flip_fraction,xai_enrichment,0.3241,0.0806
22,BA_neutral_minus_reversed,xai_enrichment,0.2469,0.1884
23,D,xai_enrichment,0.2315,0.2184
24,delta_z_hair,D,0.2167,0.2501
25,delta_z_norm,xai_enrichment,0.1852,0.3272
26,delta_z_hair,flip_fraction,0.1833,0.3322
27,delta_z_hair,BA_neutral_minus_reversed,-0.0500,0.7930

PRIMARY Δz_hair — rho-ADJUSTED ASSOCIATIONS
----------------------------------------------------------------------

,endpoint_A,endpoint_B,partial_spearman_rho_controlled_for_rho,p_value
13,delta_z_hair,xai_enrichment,0.4784,0.0075
14,delta_z_hair,delta_z_norm,0.4333,0.0168
16,delta_z_hair,delta_p,0.4000,0.0285
17,delta_z_hair,D_AUROC,0.3833,0.0365
24,delta_z_hair,D,0.2167,0.2501
26,delta_z_hair,flip_fraction,0.1833,0.3322
27,delta_z_hair,BA_neutral_minus_reversed,-0.0500,0.7930

HIGH rho-ADJUSTED ASSOCIATIONS (|partial Spearman| >= 0.7)
----------------------------------------------------------------------

,endpoint_A,endpoint_B,partial_spearman_rho_controlled_for_rho,p_value
0,delta_p,flip_fraction,0.9000,0.0
1,delta_p,D_AUROC,0.8333,0.0
2,flip_fraction,D_AUROC,0.7500,0.0
3,flip_fraction,D,0.7333,0.0
4,flip_fraction,BA_neutral_minus_reversed,0.7167,0.0

MODERATE rho-ADJUSTED ASSOCIATIONS (0.4 <= |partial Spearman| < 0.7)
----------------------------------------------------------------------

,endpoint_A,endpoint_B,partial_spearman_rho_controlled_for_rho,p_value
5,delta_z_norm,D_AUROC,0.6833,0.0000
6,delta_p,D,0.6833,0.0000
7,delta_p,BA_neutral_minus_reversed,0.6167,0.0003
8,delta_z_norm,delta_p,0.6000,0.0005
9,D,D_AUROC,0.6000,0.0005
10,delta_z_norm,flip_fraction,0.5667,0.0011
11,D_AUROC,BA_neutral_minus_reversed,0.5333,0.0024
12,D_AUROC,xai_enrichment,0.5092,0.0041
13,delta_z_hair,xai_enrichment,0.4784,0.0075
14,delta_z_hair,delta_z_norm,0.4333,0.0168
15,D,BA_neutral_minus_reversed,0.4167,0.0220

✓ Rank residualization completed
✓ Partial Spearman associations calculated
✓ Primary Δz relationships extracted
✓ Results saved

======================================================================
CELL 5 COMPLETE
======================================================================

Interpretation is intentionally deferred until the rank-equivalence and PCA audits are complete.

In [6]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 6 — EXACT RANK-EQUIVALENCE AUDIT
# ================================================================

import numpy as np
import pandas as pd
from scipy.stats import rankdata, spearmanr

print("=" * 70)
print("T1.1 — CELL 6: EXACT RANK-EQUIVALENCE AUDIT")
print("=" * 70)


# ------------------------------------------------
# Function to compare rankings
# ------------------------------------------------

def rank_equivalence(a, b):

    ra = rankdata(a, method="average")
    rb = rankdata(b, method="average")

    return {
        "spearman": spearmanr(a, b).statistic,
        "same_rank_vector": bool(np.array_equal(ra, rb)),
        "n_rank_position_differences": int(np.sum(ra != rb)),
        "max_rank_difference": float(np.max(np.abs(ra - rb))),
        "mean_abs_rank_difference":
            float(np.mean(np.abs(ra - rb))),
    }


# ------------------------------------------------
# Compare every endpoint pair
# ------------------------------------------------

rank_rows = []

for i, a in enumerate(ENDPOINTS):

    for j, b in enumerate(ENDPOINTS):

        if j <= i:
            continue

        result = rank_equivalence(
            X[a].to_numpy(),
            X[b].to_numpy()
        )

        rank_rows.append({
            "endpoint_A": a,
            "endpoint_B": b,
            **result
        })


rank_audit = (
    pd.DataFrame(rank_rows)
    .sort_values(
        ["same_rank_vector", "spearman"],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------
# Display all results
# ------------------------------------------------

print("\nALL PAIRWISE RANK-EQUIVALENCE RESULTS")
print("-" * 70)

display(
    rank_audit.round(4)
)


# ------------------------------------------------
# Exact rank-equivalent pairs
# ------------------------------------------------

exact = rank_audit[
    rank_audit["same_rank_vector"]
].copy()

print("\nEXACTLY RANK-EQUIVALENT PAIRS")
print("-" * 70)

if len(exact):
    display(exact.round(4))
else:
    print("NONE")


# ------------------------------------------------
# Near rank-equivalent pairs
# ------------------------------------------------

near = rank_audit[
    (rank_audit["spearman"] >= 0.99)
    &
    (~rank_audit["same_rank_vector"])
].copy()

print("\nNEAR-RANK-EQUIVALENT PAIRS")
print("(Spearman >= 0.99 but not identical ranking)")
print("-" * 70)

if len(near):
    display(near.round(4))
else:
    print("NONE")


# ------------------------------------------------
# Primary endpoint ranking comparisons
# ------------------------------------------------

primary_rank = rank_audit[
    (rank_audit["endpoint_A"] == "delta_z_hair")
    |
    (rank_audit["endpoint_B"] == "delta_z_hair")
].copy()

print("\nPRIMARY Δz_hair — RANK COMPARISONS")
print("-" * 70)

display(
    primary_rank.round(4)
)


# ------------------------------------------------
# Save
# ------------------------------------------------

rank_audit.to_csv(
    "T1_1_exact_rank_equivalence.csv",
    index=False
)

print("\n✓ Exact rank-equivalence audit complete")
print("✓ Near-equivalence pairs identified")
print("✓ Primary endpoint ranking comparisons extracted")
print("✓ Results saved")

print("\n" + "=" * 70)
print("CELL 6 COMPLETE")
print("=" * 70)

print(
    "\nDo not classify endpoints as independent/redundant "
    "until the PCA/effective-dimension analysis is complete."
)

======================================================================
T1.1 — CELL 6: EXACT RANK-EQUIVALENCE AUDIT
======================================================================

ALL PAIRWISE RANK-EQUIVALENCE RESULTS
----------------------------------------------------------------------

,endpoint_A,endpoint_B,spearman,same_rank_vector,n_rank_position_differences,max_rank_difference,mean_abs_rank_difference
0,delta_p,flip_fraction,0.9973,False,12,1.0,0.4000
1,delta_p,D_AUROC,0.9956,False,9,3.0,0.4000
2,flip_fraction,D_AUROC,0.9933,False,16,3.0,0.6667
3,flip_fraction,D,0.9929,False,15,3.0,0.6667
4,flip_fraction,BA_neutral_minus_reversed,0.9924,False,16,2.0,0.7333
5,delta_z_norm,D_AUROC,0.9915,False,15,3.0,0.7333
6,delta_p,D,0.9915,False,14,2.0,0.7333
7,delta_p,BA_neutral_minus_reversed,0.9898,False,19,2.0,0.9333
8,delta_z_norm,delta_p,0.9893,False,16,3.0,0.8667
9,D,D_AUROC,0.9893,False,19,3.0,0.9333
10,delta_z_norm,flip_fraction,0.9884,False,19,4.0,0.9333
11,D_AUROC,BA_neutral_minus_reversed,0.9875,False,20,4.0,1.0000
12,D_AUROC,xai_enrichment,0.9858,False,22,3.0,1.1333
13,delta_z_hair,delta_z_norm,0.9849,False,20,3.0,1.1333
14,delta_z_hair,xai_enrichment,0.9849,False,22,4.0,1.1333
15,D,BA_neutral_minus_reversed,0.9844,False,18,4.0,1.0667
16,delta_z_hair,delta_p,0.9840,False,20,4.0,1.1333
17,delta_z_hair,D_AUROC,0.9835,False,21,3.0,1.2000
18,delta_z_norm,D,0.9831,False,23,4.0,1.2667
19,delta_z_norm,BA_neutral_minus_reversed,0.9826,False,19,4.0,1.1333
20,delta_p,xai_enrichment,0.9809,False,25,4.0,1.4000
21,flip_fraction,xai_enrichment,0.9804,False,24,5.0,1.3333
22,delta_z_hair,D,0.9791,False,25,4.0,1.4000
23,delta_z_hair,flip_fraction,0.9782,False,21,4.0,1.3333
24,BA_neutral_minus_reversed,xai_enrichment,0.9782,False,22,4.0,1.4000
25,D,xai_enrichment,0.9778,False,24,5.0,1.4000
26,delta_z_norm,xai_enrichment,0.9764,False,18,4.0,1.3333
27,delta_z_hair,BA_neutral_minus_reversed,0.9720,False,25,4.0,1.6667

EXACTLY RANK-EQUIVALENT PAIRS
----------------------------------------------------------------------
NONE

NEAR-RANK-EQUIVALENT PAIRS
(Spearman >= 0.99 but not identical ranking)
----------------------------------------------------------------------

,endpoint_A,endpoint_B,spearman,same_rank_vector,n_rank_position_differences,max_rank_difference,mean_abs_rank_difference
0,delta_p,flip_fraction,0.9973,False,12,1.0,0.4000
1,delta_p,D_AUROC,0.9956,False,9,3.0,0.4000
2,flip_fraction,D_AUROC,0.9933,False,16,3.0,0.6667
3,flip_fraction,D,0.9929,False,15,3.0,0.6667
4,flip_fraction,BA_neutral_minus_reversed,0.9924,False,16,2.0,0.7333
5,delta_z_norm,D_AUROC,0.9915,False,15,3.0,0.7333
6,delta_p,D,0.9915,False,14,2.0,0.7333

PRIMARY Δz_hair — RANK COMPARISONS
----------------------------------------------------------------------

,endpoint_A,endpoint_B,spearman,same_rank_vector,n_rank_position_differences,max_rank_difference,mean_abs_rank_difference
13,delta_z_hair,delta_z_norm,0.9849,False,20,3.0,1.1333
14,delta_z_hair,xai_enrichment,0.9849,False,22,4.0,1.1333
16,delta_z_hair,delta_p,0.9840,False,20,4.0,1.1333
17,delta_z_hair,D_AUROC,0.9835,False,21,3.0,1.2000
22,delta_z_hair,D,0.9791,False,25,4.0,1.4000
23,delta_z_hair,flip_fraction,0.9782,False,21,4.0,1.3333
27,delta_z_hair,BA_neutral_minus_reversed,0.9720,False,25,4.0,1.6667

✓ Exact rank-equivalence audit complete
✓ Near-equivalence pairs identified
✓ Primary endpoint ranking comparisons extracted
✓ Results saved

======================================================================
CELL 6 COMPLETE
======================================================================

Do not classify endpoints as independent/redundant until the PCA/effective-dimension analysis is complete.

In [7]:
# ================================================================
# T1.1 — ENDPOINT REDUNDANCY AUDIT
# CELL 7 — PCA / EFFECTIVE DIMENSIONALITY
# ================================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

print("=" * 70)
print("T1.1 — CELL 7: PCA / EFFECTIVE DIMENSIONALITY")
print("=" * 70)


# ================================================================
# PART A — PCA ON RAW ENDPOINTS
# ================================================================

print("\nPART A — PCA ON RAW ENDPOINTS")
print("-" * 70)

scaler_raw = StandardScaler()

X_raw_scaled = scaler_raw.fit_transform(X)

pca_raw = PCA()

scores_raw = pca_raw.fit_transform(X_raw_scaled)

explained_raw = pca_raw.explained_variance_ratio_

pca_raw_table = pd.DataFrame({
    "PC": np.arange(1, len(ENDPOINTS) + 1),
    "eigenvalue": pca_raw.explained_variance_,
    "variance_fraction": explained_raw,
    "variance_percent": explained_raw * 100,
    "cumulative_percent":
        np.cumsum(explained_raw) * 100
})

print("\nRAW PCA VARIANCE")
display(
    pca_raw_table.round(4)
)


# ------------------------------------------------
# Raw PCA loadings
# ------------------------------------------------

loadings_raw = pd.DataFrame(
    pca_raw.components_.T,
    index=ENDPOINTS,
    columns=[
        f"PC{i}"
        for i in range(1, len(ENDPOINTS) + 1)
    ]
)

print("\nRAW PCA LOADINGS")
display(
    loadings_raw.round(4)
)


# ================================================================
# PART B — PCA AFTER REMOVING rho
# ================================================================

print("\n\nPART B — PCA AFTER REMOVING THE COMMON rho EFFECT")
print("-" * 70)

# R was created in Cell 5:
# rank-transformed endpoint residuals after rho adjustment.

scaler_resid = StandardScaler()

R_scaled = scaler_resid.fit_transform(R)

pca_resid = PCA()

scores_resid = pca_resid.fit_transform(R_scaled)

explained_resid = (
    pca_resid.explained_variance_ratio_
)

pca_resid_table = pd.DataFrame({
    "PC": np.arange(1, len(ENDPOINTS) + 1),
    "eigenvalue": pca_resid.explained_variance_,
    "variance_fraction": explained_resid,
    "variance_percent": explained_resid * 100,
    "cumulative_percent":
        np.cumsum(explained_resid) * 100
})

print("\nRHO-ADJUSTED PCA VARIANCE")
display(
    pca_resid_table.round(4)
)


# ------------------------------------------------
# rho-adjusted loadings
# ------------------------------------------------

loadings_resid = pd.DataFrame(
    pca_resid.components_.T,
    index=ENDPOINTS,
    columns=[
        f"PC{i}"
        for i in range(1, len(ENDPOINTS) + 1)
    ]
)

print("\nRHO-ADJUSTED PCA LOADINGS")
display(
    loadings_resid.round(4)
)


# ================================================================
# PART C — SIMPLE DIMENSIONALITY COUNTS
# ================================================================

def effective_dimensions(eigenvalues):

    # Kaiser criterion
    kaiser = int(np.sum(eigenvalues > 1.0))

    # 80% and 90% cumulative variance
    frac = eigenvalues / eigenvalues.sum()
    cumulative = np.cumsum(frac)

    n80 = int(np.argmax(cumulative >= 0.80) + 1)
    n90 = int(np.argmax(cumulative >= 0.90) + 1)

    return kaiser, n80, n90


k_raw, n80_raw, n90_raw = effective_dimensions(
    pca_raw.explained_variance_
)

k_resid, n80_resid, n90_resid = effective_dimensions(
    pca_resid.explained_variance_
)

print("\nDIMENSIONALITY SUMMARY")
print("-" * 70)

print(
    f"Raw endpoints:"
    f"  Kaiser={k_raw}, "
    f"PCs for 80%={n80_raw}, "
    f"PCs for 90%={n90_raw}"
)

print(
    f"rho-adjusted endpoints:"
    f"  Kaiser={k_resid}, "
    f"PCs for 80%={n80_resid}, "
    f"PCs for 90%={n90_resid}"
)


# ================================================================
# PART D — SAVE
# ================================================================

pca_raw_table.to_csv(
    "T1_1_PCA_raw_variance.csv",
    index=False
)

loadings_raw.to_csv(
    "T1_1_PCA_raw_loadings.csv"
)

pca_resid_table.to_csv(
    "T1_1_PCA_rho_adjusted_variance.csv",
    index=False
)

loadings_resid.to_csv(
    "T1_1_PCA_rho_adjusted_loadings.csv"
)

np.save(
    "T1_1_PCA_raw_scores.npy",
    scores_raw
)

np.save(
    "T1_1_PCA_rho_adjusted_scores.npy",
    scores_resid
)

print("\n✓ Raw PCA completed")
print("✓ rho-adjusted PCA completed")
print("✓ Variance tables saved")
print("✓ Loading matrices saved")
print("✓ PCA scores saved")

print("\n" + "=" * 70)
print("CELL 7 COMPLETE")
print("=" * 70)

print(
    "\nDo not make the final T1.1 conclusion yet. "
    "We still need the mechanistic Δz↔behavior audit."
)

======================================================================
T1.1 — CELL 7: PCA / EFFECTIVE DIMENSIONALITY
======================================================================

PART A — PCA ON RAW ENDPOINTS
----------------------------------------------------------------------

RAW PCA VARIANCE

   PC  eigenvalue  variance_fraction  variance_percent  cumulative_percent
0   1      8.1731             0.9876           98.7581             98.7581
1   2      0.0672             0.0081            0.8125             99.5706
2   3      0.0242             0.0029            0.2926             99.8632
3   4      0.0059             0.0007            0.0718             99.9349
4   5      0.0032             0.0004            0.0388             99.9737
5   6      0.0017             0.0002            0.0210             99.9948
6   7      0.0004             0.0000            0.0044             99.9992
7   8      0.0001             0.0000            0.0008            100.0000

RAW PCA LOADINGS

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8
delta_z_hair,0.3543,0.2041,0.2238,0.8660,-0.1238,0.0620,-0.0729,0.0913
delta_z_norm,0.3513,-0.5803,-0.2379,0.1578,0.6643,-0.1240,0.0287,0.0282
delta_p,0.3554,0.1559,-0.1113,-0.0383,-0.0970,-0.1004,0.5809,-0.6918
flip_fraction,0.3554,0.1144,-0.1754,-0.1790,-0.1717,-0.0591,0.5120,0.7090
D,0.3502,0.6747,0.0425,-0.2668,0.4793,-0.0936,-0.3325,0.0071
D_AUROC,0.3549,-0.1689,-0.2771,-0.0989,-0.4879,-0.5367,-0.4787,-0.0614
BA_neutral_minus_reversed,0.3551,-0.0982,-0.2880,-0.1433,-0.1766,0.8182,-0.2335,-0.0755
xai_enrichment,0.3517,-0.3014,0.8298,-0.3004,-0.0742,0.0312,-0.0098,-0.0065

PART B — PCA AFTER REMOVING THE COMMON rho EFFECT
----------------------------------------------------------------------

RHO-ADJUSTED PCA VARIANCE

   PC  eigenvalue  variance_fraction  variance_percent  cumulative_percent
0   1      4.6626             0.5634           56.3398             56.3398
1   2      1.3591             0.1642           16.4223             72.7621
2   3      0.8257             0.0998            9.9767             82.7388
3   4      0.6276             0.0758            7.5837             90.3225
4   5      0.3611             0.0436            4.3632             94.6857
5   6      0.2412             0.0291            2.9140             97.5997
6   7      0.1600             0.0193            1.9337             99.5333
7   8      0.0386             0.0047            0.4667            100.0000

RHO-ADJUSTED PCA LOADINGS

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8
delta_z_hair,0.2103,0.6969,-0.1798,0.1295,0.5877,-0.0714,-0.1381,-0.2270
delta_z_norm,0.3353,0.1364,-0.5874,-0.4380,-0.2937,-0.4112,0.1992,0.1924
delta_p,0.4408,-0.0719,-0.0819,0.0884,0.2266,0.5553,0.1207,0.6417
flip_fraction,0.4302,-0.2524,0.0304,0.0736,0.0759,0.1218,0.6233,-0.5795
D,0.3506,-0.1740,-0.0283,0.7516,-0.1471,-0.4607,-0.1828,0.1174
D_AUROC,0.4279,0.0729,-0.0074,-0.1230,-0.4364,0.3841,-0.5868,-0.3377
BA_neutral_minus_reversed,0.3193,-0.4160,0.3173,-0.4338,0.4655,-0.3430,-0.3180,0.0266
xai_enrichment,0.2366,0.4672,0.7166,-0.0991,-0.2871,-0.1591,0.2435,0.1881

DIMENSIONALITY SUMMARY
----------------------------------------------------------------------
Raw endpoints:  Kaiser=1, PCs for 80%=1, PCs for 90%=1
rho-adjusted endpoints:  Kaiser=2, PCs for 80%=3, PCs for 90%=4

✓ Raw PCA completed
✓ rho-adjusted PCA completed
✓ Variance tables saved
✓ Loading matrices saved
✓ PCA scores saved

======================================================================
CELL 7 COMPLETE
======================================================================

Do not make the final T1.1 conclusion yet. We still need the mechanistic Δz↔behavior audit.

In [8]:
# ======================================================================
# T1.1 — CELL 8: MECHANISTIC Δz ↔ BEHAVIOR AUDIT
# ======================================================================

import numpy as np
import pandas as pd
from pathlib import Path
from scipy.stats import spearmanr, pearsonr

print("=" * 70)
print("T1.1 — CELL 8: MECHANISTIC Δz ↔ BEHAVIOR AUDIT")
print("=" * 70)

# ----------------------------------------------------------------------
# 0. Locate the committed analysis results
# ----------------------------------------------------------------------

candidates = list(Path("/kaggle/input").rglob(
    "model_endpoints_final_checkpoint.csv"
))

assert candidates, (
    "Could not find model_endpoints_final_checkpoint.csv under /kaggle/input"
)

CSV_PATH = candidates[0]

print(f"\nUsing endpoint table:")
print(f"  {CSV_PATH}")

df = pd.read_csv(CSV_PATH)

# Save T1.1 outputs locally
RESULTS = Path("/kaggle/working/t1_1_results")
RESULTS.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# 1. Basic integrity checks
# ----------------------------------------------------------------------

assert len(df) == 30, f"Expected 30 models, found {len(df)}"

assert sorted(df["rho"].unique().tolist()) == [
    0.0, 0.2, 0.4, 0.6, 0.8, 1.0
]

assert all(
    df.groupby("rho").size().to_numpy() == 5
), "Expected exactly 5 replicates per rho"

PRIMARY = "delta_z_hair"

BEHAVIOR_ENDPOINTS = [
    "D",
    "D_AUROC",
    "BA_neutral_minus_reversed",
]

SECONDARY_ENDPOINTS = [
    "delta_z_norm",
    "delta_p",
    "flip_fraction",
    "xai_enrichment",
]

ALL_TARGETS = BEHAVIOR_ENDPOINTS + SECONDARY_ENDPOINTS

for col in [PRIMARY] + ALL_TARGETS:
    assert col in df.columns, f"Missing endpoint: {col}"
    assert np.isfinite(df[col]).all(), f"Non-finite values in {col}"

print(f"\n✓ Loaded {len(df)} model endpoints")
print("✓ Six rho levels present")
print("✓ Five replicates per rho")
print("✓ All requested endpoints finite")

# ----------------------------------------------------------------------
# 2. Pooled correlations — descriptive only
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART A — POOLED Δz ↔ ENDPOINT CORRELATIONS")
print("=" * 70)

pooled_rows = []

for target in ALL_TARGETS:

    x = df[PRIMARY].to_numpy()
    y = df[target].to_numpy()

    r_p, p_p = pearsonr(x, y)
    r_s, p_s = spearmanr(x, y)

    pooled_rows.append({
        "endpoint": target,
        "pearson_r": r_p,
        "pearson_p": p_p,
        "spearman_r": r_s,
        "spearman_p": p_s,
    })

pooled = pd.DataFrame(pooled_rows)

print(
    pooled.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# 3. Within-rho correlations
#
# IMPORTANT:
# n = 5 models per rho.
# These are diagnostic, NOT confirmatory.
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B — WITHIN-rho Δz ↔ ENDPOINT CORRELATIONS")
print("=" * 70)

within_rows = []

for rho in sorted(df["rho"].unique()):

    sub = df[df["rho"] == rho].sort_values("replicate").copy()

    assert len(sub) == 5

    for target in ALL_TARGETS:

        x = sub[PRIMARY].to_numpy()
        y = sub[target].to_numpy()

        r_p, p_p = pearsonr(x, y)
        r_s, p_s = spearmanr(x, y)

        within_rows.append({
            "rho": rho,
            "endpoint": target,
            "n": len(sub),
            "pearson_r": r_p,
            "pearson_p": p_p,
            "spearman_r": r_s,
            "spearman_p": p_s,
        })

within = pd.DataFrame(within_rows)

print(
    within[
        [
            "rho",
            "endpoint",
            "pearson_r",
            "spearman_r",
            "pearson_p",
            "spearman_p",
        ]
    ].to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# 4. Summary across rho levels
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART C — SUMMARY OF WITHIN-rho RELATIONSHIPS")
print("=" * 70)

summary_rows = []

for target in ALL_TARGETS:

    sub = within[within["endpoint"] == target]

    summary_rows.append({
        "endpoint": target,

        "mean_spearman": sub["spearman_r"].mean(),
        "median_spearman": sub["spearman_r"].median(),
        "min_spearman": sub["spearman_r"].min(),
        "max_spearman": sub["spearman_r"].max(),

        "mean_pearson": sub["pearson_r"].mean(),
        "median_pearson": sub["pearson_r"].median(),
        "min_pearson": sub["pearson_r"].min(),
        "max_pearson": sub["pearson_r"].max(),

        "n_positive_spearman": int(
            (sub["spearman_r"] > 0).sum()
        ),

        "n_negative_spearman": int(
            (sub["spearman_r"] < 0).sum()
        ),
    })

within_summary = pd.DataFrame(summary_rows)

print(
    within_summary.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# 5. Directional consistency
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART D — DIRECTIONAL CONSISTENCY")
print("=" * 70)

for target in ALL_TARGETS:

    sub = within[within["endpoint"] == target]

    positive = int(
        (sub["spearman_r"] > 0).sum()
    )

    negative = int(
        (sub["spearman_r"] < 0).sum()
    )

    print(
        f"{target:30s} "
        f"positive={positive}/6, "
        f"negative={negative}/6, "
        f"median_rho={sub['spearman_r'].median():+.3f}"
    )

# ----------------------------------------------------------------------
# 6. Primary mechanistic audit
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART E — PRIMARY MECHANISTIC AUDIT")
print("=" * 70)

for target in BEHAVIOR_ENDPOINTS:

    sub = within[within["endpoint"] == target]

    print(f"\n{target}")
    print("-" * len(target))

    print(
        f"Mean within-rho Spearman : "
        f"{sub['spearman_r'].mean():+.4f}"
    )

    print(
        f"Median within-rho Spearman : "
        f"{sub['spearman_r'].median():+.4f}"
    )

    print(
        f"Range : "
        f"[{sub['spearman_r'].min():+.4f}, "
        f"{sub['spearman_r'].max():+.4f}]"
    )

    print(
        f"Positive rho-levels : "
        f"{int((sub['spearman_r'] > 0).sum())}/6"
    )

# ----------------------------------------------------------------------
# 7. Save
# ----------------------------------------------------------------------

pooled.to_csv(
    RESULTS / "pooled_delta_z_relationships.csv",
    index=False
)

within.to_csv(
    RESULTS / "within_rho_delta_z_relationships.csv",
    index=False
)

within_summary.to_csv(
    RESULTS / "within_rho_delta_z_summary.csv",
    index=False
)

print("\n" + "=" * 70)
print("CELL 8 COMPLETE")
print("=" * 70)

print(f"\nSaved to: {RESULTS}")
print("\nDo not make the final T1.1 conclusion yet.")
print("Next we will inspect mathematical coupling among")
print("D, D_AUROC, BA differences, flips, and predictions.")

======================================================================
T1.1 — CELL 8: MECHANISTIC Δz ↔ BEHAVIOR AUDIT
======================================================================

Using endpoint table:
  /kaggle/input/notebooks/tejasseshadriiiii/isic-kaggle-analysis/results/model_endpoints_final_checkpoint.csv

✓ Loaded 30 model endpoints
✓ Six rho levels present
✓ Five replicates per rho
✓ All requested endpoints finite

======================================================================
PART A — POOLED Δz ↔ ENDPOINT CORRELATIONS
======================================================================
                 endpoint  pearson_r  pearson_p  spearman_r  spearman_p
                        D     0.9881     0.0000      0.9791      0.0000
                  D_AUROC     0.9893     0.0000      0.9835      0.0000
BA_neutral_minus_reversed     0.9905     0.0000      0.9720      0.0000
             delta_z_norm     0.9750     0.0000      0.9849      0.0000
                  delta_p     0.9961     0.0000      0.9840      0.0000
            flip_fraction     0.9946     0.0000      0.9782      0.0000
           xai_enrichment     0.9835     0.0000      0.9849      0.0000

======================================================================
PART B — WITHIN-rho Δz ↔ ENDPOINT CORRELATIONS
======================================================================
   rho                  endpoint  pearson_r  spearman_r  pearson_p  spearman_p
0.0000                         D     0.6855      0.7000     0.2014      0.1881
0.0000                   D_AUROC     0.9919      1.0000     0.0009      0.0000
0.0000 BA_neutral_minus_reversed     0.7675      0.7000     0.1297      0.1881
0.0000              delta_z_norm     0.9562      0.9000     0.0109      0.0374
0.0000                   delta_p     0.9423      0.9000     0.0165      0.0374
0.0000             flip_fraction     0.9261      0.9000     0.0239      0.0374
0.0000            xai_enrichment     0.8439      0.8000     0.0723      0.1041
0.2000                         D    -0.0193     -0.1000     0.9754      0.8729
0.2000                   D_AUROC     0.3342      0.3000     0.5826      0.6238
0.2000 BA_neutral_minus_reversed     0.2041     -0.1000     0.7420      0.8729
0.2000              delta_z_norm     0.7919      0.6000     0.1103      0.2848
0.2000                   delta_p     0.0007     -0.1000     0.9991      0.8729
0.2000             flip_fraction     0.1729     -0.1000     0.7810      0.8729
0.2000            xai_enrichment     0.5310      0.3000     0.3572      0.6238
0.4000                         D    -0.5913     -0.4000     0.2936      0.5046
0.4000                   D_AUROC    -0.1185      0.1000     0.8495      0.8729
0.4000 BA_neutral_minus_reversed    -0.7935     -0.7000     0.1091      0.1881
0.4000              delta_z_norm     0.1669      0.3000     0.7885      0.6238
0.4000                   delta_p    -0.3726      0.1000     0.5368      0.8729
0.4000             flip_fraction    -0.4834     -0.5000     0.4094      0.3910
0.4000            xai_enrichment    -0.1543     -0.1000     0.8043      0.8729
0.6000                         D     0.5780      0.4000     0.3074      0.5046
0.6000                   D_AUROC    -0.0599     -0.2000     0.9238      0.7471
0.6000 BA_neutral_minus_reversed     0.0184     -0.1000     0.9765      0.8729
0.6000              delta_z_norm     0.0705     -0.1000     0.9103      0.8729
0.6000                   delta_p     0.3491      0.3000     0.5647      0.6238
0.6000             flip_fraction     0.1318      0.1000     0.8327      0.8729
0.6000            xai_enrichment     0.6445      0.7000     0.2404      0.1881
0.8000                         D     0.5567      0.5000     0.3298      0.3910
0.8000                   D_AUROC     0.7672      0.8000     0.1300      0.1041
0.8000 BA_neutral_minus_reversed     0.1725      0.1000     0.7814      0.8729
0.8000              delta_z_norm     0.5893      0.6000     0.2957      0.2848
0.8000                   delta_p     0.7424      0.9000     0.1508      0.0374
0.8000             flip_fraction     0.6193      0.6000     0.2653      0.2848
0.8000            xai_enrichment     0.4295      0.6000     0.4705      0.2848
1.0000                         D     0.0208      0.2000     0.9735      0.7471
1.0000                   D_AUROC     0.0711      0.3000     0.9096      0.6238
1.0000 BA_neutral_minus_reversed    -0.2760     -0.2000     0.6531      0.7471
1.0000              delta_z_norm     0.3267      0.3000     0.5915      0.6238
1.0000                   delta_p     0.1905      0.3000     0.7589      0.6238
1.0000             flip_fraction    -0.1669      0.1000     0.7884      0.8729
1.0000            xai_enrichment     0.6581      0.7000     0.2272      0.1881

======================================================================
PART C — SUMMARY OF WITHIN-rho RELATIONSHIPS
======================================================================
                 endpoint  mean_spearman  median_spearman  min_spearman  max_spearman  mean_pearson  median_pearson  min_pearson  max_pearson  n_positive_spearman  n_negative_spearman
                        D         0.2167           0.3000       -0.4000        0.7000        0.2051          0.2887      -0.5913       0.6855                    4                    2
                  D_AUROC         0.3833           0.3000       -0.2000        1.0000        0.3310          0.2026      -0.1185       0.9919                    5                    1
BA_neutral_minus_reversed        -0.0500          -0.1000       -0.7000        0.7000        0.0155          0.0955      -0.7935       0.7675                    2                    4
             delta_z_norm         0.4333           0.4500       -0.1000        0.9000        0.4836          0.4580       0.0705       0.9562                    5                    1
                  delta_p         0.4000           0.3000       -0.1000        0.9000        0.3087          0.2698      -0.3726       0.9423                    5                    1
            flip_fraction         0.1833           0.1000       -0.5000        0.9000        0.1999          0.1523      -0.4834       0.9261                    4                    2
           xai_enrichment         0.5000           0.6500       -0.1000        0.8000        0.4921          0.5878      -0.1543       0.8439                    5                    1

======================================================================
PART D — DIRECTIONAL CONSISTENCY
======================================================================
D                              positive=4/6, negative=2/6, median_rho=+0.300
D_AUROC                        positive=5/6, negative=1/6, median_rho=+0.300
BA_neutral_minus_reversed      positive=2/6, negative=4/6, median_rho=-0.100
delta_z_norm                   positive=5/6, negative=1/6, median_rho=+0.450
delta_p                        positive=5/6, negative=1/6, median_rho=+0.300
flip_fraction                  positive=4/6, negative=2/6, median_rho=+0.100
xai_enrichment                 positive=5/6, negative=1/6, median_rho=+0.650

======================================================================
PART E — PRIMARY MECHANISTIC AUDIT
======================================================================

D
-
Mean within-rho Spearman : +0.2167
Median within-rho Spearman : +0.3000
Range : [-0.4000, +0.7000]
Positive rho-levels : 4/6

D_AUROC
-------
Mean within-rho Spearman : +0.3833
Median within-rho Spearman : +0.3000
Range : [-0.2000, +1.0000]
Positive rho-levels : 5/6

BA_neutral_minus_reversed
-------------------------
Mean within-rho Spearman : -0.0500
Median within-rho Spearman : -0.1000
Range : [-0.7000, +0.7000]
Positive rho-levels : 2/6

======================================================================
CELL 8 COMPLETE
======================================================================

Saved to: /kaggle/working/t1_1_results

Do not make the final T1.1 conclusion yet.
Next we will inspect mathematical coupling among
D, D_AUROC, BA differences, flips, and predictions.

In [9]:
# ======================================================================
# T1.1 — CELL 9: MATHEMATICAL COUPLING AUDIT
# ======================================================================

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr

print("=" * 70)
print("T1.1 — CELL 9: MATHEMATICAL COUPLING AUDIT")
print("=" * 70)

# ----------------------------------------------------------------------
# 0. Load endpoint table
# ----------------------------------------------------------------------

CSV_PATH = "/kaggle/input/notebooks/tejasseshadriiiii/isic-kaggle-analysis/results/model_endpoints_final_checkpoint.csv"

df = pd.read_csv(CSV_PATH)

assert len(df) == 30

# ----------------------------------------------------------------------
# PART A — Verify algebraic identities
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART A — ALGEBRAIC IDENTITY CHECKS")
print("=" * 70)

# D is defined as BA(clean) - BA(reversed)
D_reconstructed = (
    df["BA_clean"] - df["BA_reversed"]
)

err_D = np.abs(
    D_reconstructed - df["D"]
)

print("\nD = BA_clean - BA_reversed")
print(f"Maximum absolute reconstruction error: {err_D.max():.12g}")
print(f"Mean absolute reconstruction error   : {err_D.mean():.12g}")

assert err_D.max() < 1e-10

# Neutral-minus-reversed
NMR_reconstructed = (
    df["BA_neutral"] - df["BA_reversed"]
)

err_NMR = np.abs(
    NMR_reconstructed - df["BA_neutral_minus_reversed"]
)

print("\nBA_neutral_minus_reversed = BA_neutral - BA_reversed")
print(f"Maximum absolute reconstruction error: {err_NMR.max():.12g}")
print(f"Mean absolute reconstruction error   : {err_NMR.mean():.12g}")

assert err_NMR.max() < 1e-10

# Exact relationship between D and neutral-minus-reversed
clean_minus_neutral = (
    df["BA_clean"] - df["BA_neutral"]
)

identity_residual = (
    df["D"]
    - df["BA_neutral_minus_reversed"]
    - clean_minus_neutral
)

print("\nD - (BA_neutral_minus_reversed) = BA_clean - BA_neutral")
print(f"Maximum absolute identity error: {np.abs(identity_residual).max():.12g}")

assert np.abs(identity_residual).max() < 1e-10

# ----------------------------------------------------------------------
# PART B — Direct correlations among behavioral endpoints
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B — BEHAVIORAL ENDPOINT CORRELATIONS")
print("=" * 70)

behavior = [
    "D",
    "D_AUROC",
    "BA_neutral_minus_reversed",
    "BA_clean",
    "BA_reversed",
    "BA_neutral",
]

corr_rows = []

for i in range(len(behavior)):
    for j in range(i + 1, len(behavior)):

        a = behavior[i]
        b = behavior[j]

        r_p, p_p = pearsonr(df[a], df[b])
        r_s, p_s = spearmanr(df[a], df[b])

        corr_rows.append({
            "endpoint_A": a,
            "endpoint_B": b,
            "pearson_r": r_p,
            "spearman_r": r_s,
            "pearson_p": p_p,
            "spearman_p": p_s,
        })

behavior_corr = pd.DataFrame(corr_rows)

print(
    behavior_corr.sort_values(
        "spearman_r",
        key=lambda s: np.abs(s),
        ascending=False
    ).to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# PART C — The D vs neutral-minus-reversed decomposition
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART C — D DECOMPOSITION")
print("=" * 70)

decomp = pd.DataFrame({
    "model": df["model"],
    "rho": df["rho"],
    "replicate": df["replicate"],

    "D": df["D"],

    "BA_neutral_minus_reversed":
        df["BA_neutral_minus_reversed"],

    "BA_clean_minus_neutral":
        clean_minus_neutral,

    "D_reconstructed":
        df["BA_neutral_minus_reversed"] + clean_minus_neutral,
})

decomp["reconstruction_error"] = (
    decomp["D"] - decomp["D_reconstructed"]
)

print(
    decomp[
        [
            "rho",
            "replicate",
            "D",
            "BA_neutral_minus_reversed",
            "BA_clean_minus_neutral",
            "reconstruction_error",
        ]
    ].to_string(
        index=False,
        float_format=lambda x: f"{x:.5f}"
    )
)

# Correlations of the two components with D
for target in [
    "BA_neutral_minus_reversed",
    "BA_clean_minus_neutral",
]:

    r_p, p_p = pearsonr(decomp["D"], decomp[target])
    r_s, p_s = spearmanr(decomp["D"], decomp[target])

    print(
        f"\nD ↔ {target}"
    )
    print(f"Pearson  r = {r_p:+.4f}, p = {p_p:.4g}")
    print(f"Spearman r = {r_s:+.4f}, p = {p_s:.4g}")

# ----------------------------------------------------------------------
# PART D — Within-rho decomposition
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART D — WITHIN-rho D DECOMPOSITION")
print("=" * 70)

within_rows = []

for rho in sorted(df["rho"].unique()):

    sub = decomp[decomp["rho"] == rho]

    for target in [
        "BA_neutral_minus_reversed",
        "BA_clean_minus_neutral",
    ]:

        if sub[target].nunique() > 1 and sub["D"].nunique() > 1:

            r_s, p_s = spearmanr(
                sub["D"],
                sub[target]
            )

            r_p, p_p = pearsonr(
                sub["D"],
                sub[target]
            )

        else:
            r_s = np.nan
            p_s = np.nan
            r_p = np.nan
            p_p = np.nan

        within_rows.append({
            "rho": rho,
            "component": target,
            "pearson_r": r_p,
            "spearman_r": r_s,
            "pearson_p": p_p,
            "spearman_p": p_s,
        })

within_decomp = pd.DataFrame(within_rows)

print(
    within_decomp.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# PART E — D vs D_AUROC: are they independently varying?
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART E — D vs D_AUROC")
print("=" * 70)

r_p, p_p = pearsonr(df["D"], df["D_AUROC"])
r_s, p_s = spearmanr(df["D"], df["D_AUROC"])

print(f"Pooled Pearson  : {r_p:+.4f}, p={p_p:.4g}")
print(f"Pooled Spearman : {r_s:+.4f}, p={p_s:.4g}")

rows = []

for rho in sorted(df["rho"].unique()):

    sub = df[df["rho"] == rho]

    r_p, p_p = pearsonr(
        sub["D"],
        sub["D_AUROC"]
    )

    r_s, p_s = spearmanr(
        sub["D"],
        sub["D_AUROC"]
    )

    rows.append({
        "rho": rho,
        "pearson_r": r_p,
        "spearman_r": r_s,
        "pearson_p": p_p,
        "spearman_p": p_s,
    })

within_D_AUROC = pd.DataFrame(rows)

print("\nWithin-rho:")
print(
    within_D_AUROC.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# PART F — Flip fraction vs D
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART F — FLIP FRACTION vs BEHAVIORAL HARM")
print("=" * 70)

for target in [
    "D",
    "D_AUROC",
    "BA_neutral_minus_reversed",
]:

    r_p, p_p = pearsonr(
        df["flip_fraction"],
        df[target]
    )

    r_s, p_s = spearmanr(
        df["flip_fraction"],
        df[target]
    )

    print(f"\nflip_fraction ↔ {target}")
    print(f"Pearson  r = {r_p:+.4f}, p={p_p:.4g}")
    print(f"Spearman r = {r_s:+.4f}, p={p_s:.4g}")

# ----------------------------------------------------------------------
# PART G — Save everything
# ----------------------------------------------------------------------

OUT = "/kaggle/working/t1_1_results"

behavior_corr.to_csv(
    f"{OUT}/behavior_endpoint_correlations.csv",
    index=False
)

decomp.to_csv(
    f"{OUT}/D_decomposition.csv",
    index=False
)

within_decomp.to_csv(
    f"{OUT}/within_rho_D_decomposition.csv",
    index=False
)

within_D_AUROC.to_csv(
    f"{OUT}/within_rho_D_vs_D_AUROC.csv",
    index=False
)

print("\n" + "=" * 70)
print("CELL 9 COMPLETE")
print("=" * 70)

print("""
Do not make the final T1.1 conclusion yet.

Next audit:
prediction-level coupling / derivation of flip_fraction,
D, and D_AUROC from the underlying logits and predictions.
""")

======================================================================
T1.1 — CELL 9: MATHEMATICAL COUPLING AUDIT
======================================================================

======================================================================
PART A — ALGEBRAIC IDENTITY CHECKS
======================================================================

D = BA_clean - BA_reversed
Maximum absolute reconstruction error: 1.38777878078e-16
Mean absolute reconstruction error   : 5.7361522939e-17

BA_neutral_minus_reversed = BA_neutral - BA_reversed
Maximum absolute reconstruction error: 8.32667268469e-17
Mean absolute reconstruction error   : 3.90891023253e-17

D - (BA_neutral_minus_reversed) = BA_clean - BA_neutral
Maximum absolute identity error: 8.32667268469e-17

======================================================================
PART B — BEHAVIORAL ENDPOINT CORRELATIONS
======================================================================
               endpoint_A                endpoint_B  pearson_r  spearman_r  pearson_p  spearman_p
              BA_reversed                BA_neutral     0.9932      0.9938     0.0000      0.0000
                  D_AUROC               BA_reversed    -0.9983     -0.9920     0.0000      0.0000
                 BA_clean               BA_reversed     0.9738      0.9915     0.0000      0.0000
BA_neutral_minus_reversed               BA_reversed    -0.9971     -0.9911     0.0000      0.0000
                 BA_clean                BA_neutral     0.9887      0.9902     0.0000      0.0000
                        D                   D_AUROC     0.9739      0.9893     0.0000      0.0000
                  D_AUROC BA_neutral_minus_reversed     0.9981      0.9875     0.0000      0.0000
                  D_AUROC                BA_neutral    -0.9874     -0.9867     0.0000      0.0000
BA_neutral_minus_reversed                  BA_clean    -0.9570     -0.9858     0.0000      0.0000
                        D BA_neutral_minus_reversed     0.9778      0.9844     0.0000      0.0000
                  D_AUROC                  BA_clean    -0.9625     -0.9813     0.0000      0.0000
                        D               BA_reversed    -0.9643     -0.9813     0.0000      0.0000
BA_neutral_minus_reversed                BA_neutral    -0.9815     -0.9809     0.0000      0.0000
                        D                BA_neutral    -0.9326     -0.9751     0.0000      0.0000
                        D                  BA_clean    -0.8788     -0.9680     0.0000      0.0000

======================================================================
PART C — D DECOMPOSITION
======================================================================
    rho  replicate       D  BA_neutral_minus_reversed  BA_clean_minus_neutral  reconstruction_error
0.60000          2 0.14837                    0.14635                 0.00202              -0.00000
0.80000          3 0.19242                    0.20174                -0.00932               0.00000
1.00000          5 0.19818                    0.26328                -0.06509              -0.00000
0.00000          5 0.01975                    0.01852                 0.00123              -0.00000
1.00000          3 0.19836                    0.26887                -0.07051              -0.00000
0.60000          4 0.14243                    0.14899                -0.00655               0.00000
0.80000          2 0.17616                    0.19829                -0.02213               0.00000
0.20000          4 0.09315                    0.09049                 0.00266              -0.00000
0.20000          1 0.08773                    0.08107                 0.00666               0.00000
0.40000          3 0.11377                    0.11312                 0.00065              -0.00000
0.40000          1 0.09874                    0.10937                -0.01063               0.00000
0.00000          4 0.02097                    0.02513                -0.00416              -0.00000
0.00000          2 0.02045                    0.02293                -0.00249               0.00000
1.00000          4 0.21548                    0.27641                -0.06093              -0.00000
0.60000          1 0.14296                    0.14764                -0.00468               0.00000
0.00000          1 0.02115                    0.02689                -0.00574              -0.00000
0.00000          3 0.02534                    0.03674                -0.01140              -0.00000
0.40000          4 0.11465                    0.11095                 0.00370               0.00000
0.60000          5 0.13160                    0.14343                -0.01183              -0.00000
0.80000          1 0.17389                    0.20318                -0.02929               0.00000
0.80000          4 0.17407                    0.19673                -0.02267               0.00000
0.20000          2 0.09595                    0.09627                -0.00033              -0.00000
0.20000          3 0.08214                    0.07785                 0.00429               0.00000
0.60000          3 0.14698                    0.14187                 0.00510              -0.00000
0.40000          5 0.10940                    0.10926                 0.00014              -0.00000
0.20000          5 0.09035                    0.08557                 0.00479               0.00000
1.00000          2 0.20587                    0.25423                -0.04835              -0.00000
1.00000          1 0.20710                    0.25958                -0.05248              -0.00000
0.80000          5 0.17704                    0.19821                -0.02117              -0.00000
0.40000          2 0.09927                    0.10350                -0.00423               0.00000

D ↔ BA_neutral_minus_reversed
Pearson  r = +0.9778, p = 1.505e-20
Spearman r = +0.9844, p = 1.099e-22

D ↔ BA_clean_minus_neutral
Pearson  r = -0.6829, p = 3.206e-05
Spearman r = -0.6685, p = 5.395e-05

======================================================================
PART D — WITHIN-rho D DECOMPOSITION
======================================================================
   rho                 component  pearson_r  spearman_r  pearson_p  spearman_p
0.0000 BA_neutral_minus_reversed     0.9725      1.0000     0.0054      0.0000
0.0000    BA_clean_minus_neutral    -0.9409     -1.0000     0.0171      0.0000
0.2000 BA_neutral_minus_reversed     0.9659      1.0000     0.0075      0.0000
0.2000    BA_clean_minus_neutral    -0.6881     -0.7000     0.1990      0.1881
0.4000 BA_neutral_minus_reversed     0.7511      0.6000     0.1434      0.2848
0.4000    BA_clean_minus_neutral     0.9055      1.0000     0.0344      0.0000
0.6000 BA_neutral_minus_reversed     0.1562     -0.2000     0.8019      0.7471
0.6000    BA_clean_minus_neutral     0.9031      0.9000     0.0357      0.0374
0.8000 BA_neutral_minus_reversed     0.3689     -0.1000     0.5412      0.8729
0.8000    BA_clean_minus_neutral     0.9376      1.0000     0.0185      0.0000
1.0000 BA_neutral_minus_reversed     0.3465      0.2000     0.5678      0.7471
1.0000    BA_clean_minus_neutral     0.4647      0.5000     0.4304      0.3910

======================================================================
PART E — D vs D_AUROC
======================================================================
Pooled Pearson  : +0.9739, p=1.429e-19
Pooled Spearman : +0.9893, p=5.753e-25

Within-rho:
   rho  pearson_r  spearman_r  pearson_p  spearman_p
0.0000     0.6109      0.7000     0.2737      0.1881
0.2000     0.8722      0.9000     0.0538      0.0374
0.4000     0.8348      0.7000     0.0786      0.1881
0.6000    -0.2272     -0.1000     0.7132      0.8729
0.8000     0.4836      0.7000     0.4092      0.1881
1.0000     0.4624      0.7000     0.4330      0.1881

======================================================================
PART F — FLIP FRACTION vs BEHAVIORAL HARM
======================================================================

flip_fraction ↔ D
Pearson  r = +0.9883, p=2.024e-24
Spearman r = +0.9929, p=2.014e-27

flip_fraction ↔ D_AUROC
Pearson  r = +0.9967, p=4.154e-32
Spearman r = +0.9933, p=8.18e-28

flip_fraction ↔ BA_neutral_minus_reversed
Pearson  r = +0.9976, p=4.687e-34
Spearman r = +0.9924, p=4.693e-27

======================================================================
CELL 9 COMPLETE
======================================================================

Do not make the final T1.1 conclusion yet.

Next audit:
prediction-level coupling / derivation of flip_fraction,
D, and D_AUROC from the underlying logits and predictions.

In [10]:
# ======================================================================
# T1.1 — CELL 10: PREDICTION-LEVEL COUPLING AUDIT
# ======================================================================

import numpy as np
import pandas as pd
from pathlib import Path
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import balanced_accuracy_score, roc_auc_score

print("=" * 70)
print("T1.1 — CELL 10: PREDICTION-LEVEL COUPLING AUDIT")
print("=" * 70)

# ----------------------------------------------------------------------
# 0. Locate committed final-checkpoint logit files
# ----------------------------------------------------------------------

CSV_PATH = Path(
    "/kaggle/input/notebooks/tejasseshadriiiii/"
    "isic-kaggle-analysis/results/"
    "model_endpoints_final_checkpoint.csv"
)

df_ref = pd.read_csv(CSV_PATH)

assert len(df_ref) == 30

print("\nSearching for final-checkpoint logit files...")

npz_candidates = list(
    Path("/kaggle/input").rglob("*__final.npz")
)

print(f"Found {len(npz_candidates)} candidate __final.npz files")

assert len(npz_candidates) >= 30, (
    "Could not find at least 30 final-checkpoint logit files. "
    "The committed analysis outputs containing results/logits "
    "must be attached to this notebook."
)

# ----------------------------------------------------------------------
# 1. Locate eval labels
# ----------------------------------------------------------------------

eval_candidates = list(
    Path("/kaggle/input").rglob("eval_y.npy")
)

assert eval_candidates, "Could not locate eval_y.npy"

EVAL_Y_PATH = eval_candidates[0]

y = np.load(EVAL_Y_PATH).astype(int)

print(f"\nEvaluation labels:")
print(f"  {EVAL_Y_PATH}")
print(f"  N = {len(y)}")
print(f"  Positive = {y.sum()}")
print(f"  Negative = {len(y) - y.sum()}")

# ----------------------------------------------------------------------
# 2. Match the correct 30 models
# ----------------------------------------------------------------------

run_names = set(
    df_ref["model"].astype(str).tolist()
)

logit_map = {}

for p in npz_candidates:

    name = p.name.replace("__final.npz", "")

    if name in run_names:
        logit_map[name] = p

print(f"\nMatched final-checkpoint logits: {len(logit_map)}/30")

missing = sorted(run_names - set(logit_map))

assert not missing, (
    "Missing final logits for:\n" +
    "\n".join(missing)
)

# ----------------------------------------------------------------------
# 3. Reconstruction functions
# ----------------------------------------------------------------------

def prediction_from_logit(z):
    """
    Binary classifier convention used by the analysis:
    z = z_M - z_B

    z >= 0 -> malignant
    z <  0 -> benign
    """
    return (z >= 0).astype(int)


def reconstruct_model(name, path):

    z = np.load(path)

    required = [
        "z_clean",
        "z_hair",
        "z_reversed",
        "z_matched",
        "z_neutral",
    ]

    for k in required:
        assert k in z.files, (
            f"{name}: missing {k}"
        )

    z_clean = z["z_clean"]
    z_hair = z["z_hair"]
    z_reversed = z["z_reversed"]
    z_matched = z["z_matched"]
    z_neutral = z["z_neutral"]

    assert len(z_clean) == len(y)
    assert len(z_hair) == len(y)
    assert len(z_reversed) == len(y)
    assert len(z_matched) == len(y)
    assert len(z_neutral) == len(y)

    # Predictions
    p_clean = prediction_from_logit(z_clean)
    p_hair = prediction_from_logit(z_hair)
    p_reversed = prediction_from_logit(z_reversed)
    p_matched = prediction_from_logit(z_matched)
    p_neutral = prediction_from_logit(z_neutral)

    # Counterfactual clean -> hair flips
    flip_fraction = np.mean(
        p_clean != p_hair
    )

    # Balanced accuracies
    BA_clean = balanced_accuracy_score(
        y,
        p_clean
    )

    BA_reversed = balanced_accuracy_score(
        y,
        p_reversed
    )

    BA_matched = balanced_accuracy_score(
        y,
        p_matched
    )

    BA_neutral = balanced_accuracy_score(
        y,
        p_neutral
    )

    # Primary behavioral degradation
    D = BA_clean - BA_reversed

    # AUROC
    # z itself is the ranking score.
    AUROC_clean = roc_auc_score(
        y,
        z_clean
    )

    AUROC_reversed = roc_auc_score(
        y,
        z_reversed
    )

    AUROC_matched = roc_auc_score(
        y,
        z_matched
    )

    AUROC_neutral = roc_auc_score(
        y,
        z_neutral
    )

    D_AUROC = (
        AUROC_clean -
        AUROC_reversed
    )

    BA_neutral_minus_reversed = (
        BA_neutral -
        BA_reversed
    )

    return {
        "model": name,

        "flip_fraction_reconstructed":
            flip_fraction,

        "BA_clean_reconstructed":
            BA_clean,

        "BA_reversed_reconstructed":
            BA_reversed,

        "BA_matched_reconstructed":
            BA_matched,

        "BA_neutral_reconstructed":
            BA_neutral,

        "D_reconstructed":
            D,

        "AUROC_clean_reconstructed":
            AUROC_clean,

        "AUROC_reversed_reconstructed":
            AUROC_reversed,

        "AUROC_matched_reconstructed":
            AUROC_matched,

        "AUROC_neutral_reconstructed":
            AUROC_neutral,

        "D_AUROC_reconstructed":
            D_AUROC,

        "BA_neutral_minus_reversed_reconstructed":
            BA_neutral_minus_reversed,
    }


# ----------------------------------------------------------------------
# 4. Reconstruct all 30 models
# ----------------------------------------------------------------------

rows = []

for name in sorted(run_names):

    row = reconstruct_model(
        name,
        logit_map[name]
    )

    rows.append(row)

recon = pd.DataFrame(rows)

# ----------------------------------------------------------------------
# 5. Verify exact agreement with frozen endpoint table
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART A — RECONSTRUCTION AGAINST FROZEN ENDPOINTS")
print("=" * 70)

merged = (
    df_ref[
        [
            "model",
            "flip_fraction",
            "BA_clean",
            "BA_reversed",
            "BA_matched",
            "BA_neutral",
            "D",
            "AUROC_clean",
            "AUROC_reversed",
            "AUROC_matched",
            "AUROC_neutral",
            "D_AUROC",
            "BA_neutral_minus_reversed",
        ]
    ]
    .merge(
        recon,
        on="model",
        how="inner"
    )
)

assert len(merged) == 30

checks = [
    ("flip_fraction",
     "flip_fraction_reconstructed"),

    ("BA_clean",
     "BA_clean_reconstructed"),

    ("BA_reversed",
     "BA_reversed_reconstructed"),

    ("BA_matched",
     "BA_matched_reconstructed"),

    ("BA_neutral",
     "BA_neutral_reconstructed"),

    ("D",
     "D_reconstructed"),

    ("AUROC_clean",
     "AUROC_clean_reconstructed"),

    ("AUROC_reversed",
     "AUROC_reversed_reconstructed"),

    ("AUROC_matched",
     "AUROC_matched_reconstructed"),

    ("AUROC_neutral",
     "AUROC_neutral_reconstructed"),

    ("D_AUROC",
     "D_AUROC_reconstructed"),

    ("BA_neutral_minus_reversed",
     "BA_neutral_minus_reversed_reconstructed"),
]

for original, reconstructed in checks:

    diff = np.abs(
        merged[original].to_numpy()
        -
        merged[reconstructed].to_numpy()
    )

    print(
        f"{original:35s} "
        f"max_abs_error={diff.max():.3e}"
    )

    assert diff.max() < 1e-10

print("\n✓ All prediction-level quantities exactly reproduce")
print("  the frozen endpoint table.")

# ----------------------------------------------------------------------
# 6. Pooled prediction-level correlations
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B — POOLED PREDICTION-LEVEL CORRELATIONS")
print("=" * 70)

prediction_targets = [
    "D",
    "D_AUROC",
    "BA_neutral_minus_reversed",
]

pooled_rows = []

for target in prediction_targets:

    r_p, p_p = pearsonr(
        merged["flip_fraction"],
        merged[target]
    )

    r_s, p_s = spearmanr(
        merged["flip_fraction"],
        merged[target]
    )

    pooled_rows.append({
        "target": target,
        "pearson_r": r_p,
        "pearson_p": p_p,
        "spearman_r": r_s,
        "spearman_p": p_s,
    })

pooled_prediction = pd.DataFrame(
    pooled_rows
)

print(
    pooled_prediction.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# 7. Within-rho prediction-level correlations
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART C — WITHIN-rho PREDICTION-LEVEL CORRELATIONS")
print("=" * 70)

within_rows = []

for rho in sorted(
    df_ref["rho"].unique()
):

    names = df_ref[
        df_ref["rho"] == rho
    ]["model"]

    sub = merged[
        merged["model"].isin(names)
    ]

    for target in prediction_targets:

        r_p, p_p = pearsonr(
            sub["flip_fraction"],
            sub[target]
        )

        r_s, p_s = spearmanr(
            sub["flip_fraction"],
            sub[target]
        )

        within_rows.append({
            "rho": rho,
            "target": target,
            "pearson_r": r_p,
            "spearman_r": r_s,
            "pearson_p": p_p,
            "spearman_p": p_s,
        })

within_prediction = pd.DataFrame(
    within_rows
)

print(
    within_prediction.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# 8. Direct image-level overlap analysis
#
# This asks:
# Among images whose clean -> hair prediction flips,
# how does that relate to the reversed-association behavior?
#
# This is descriptive only.
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART D — IMAGE-LEVEL FLIP CHARACTERIZATION")
print("=" * 70)

image_rows = []

for name in sorted(run_names):

    z = np.load(logit_map[name])

    p_clean = prediction_from_logit(
        z["z_clean"]
    )

    p_hair = prediction_from_logit(
        z["z_hair"]
    )

    p_reversed = prediction_from_logit(
        z["z_reversed"]
    )

    flips = p_clean != p_hair

    # Direction of clean -> hair flip
    benign_to_malignant = (
        (p_clean == 0) &
        (p_hair == 1)
    )

    malignant_to_benign = (
        (p_clean == 1) &
        (p_hair == 0)
    )

    image_rows.append({
        "model": name,
        "n_flips": int(flips.sum()),
        "flip_fraction": float(flips.mean()),
        "benign_to_malignant_fraction":
            float(benign_to_malignant.mean()),
        "malignant_to_benign_fraction":
            float(malignant_to_benign.mean()),
        "fraction_flips_B_to_M":
            float(
                benign_to_malignant.sum()
                /
                max(flips.sum(), 1)
            ),
        "fraction_flips_M_to_B":
            float(
                malignant_to_benign.sum()
                /
                max(flips.sum(), 1)
            ),
    })

image_flip = pd.DataFrame(
    image_rows
)

print(
    image_flip.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ----------------------------------------------------------------------
# 9. Save
# ----------------------------------------------------------------------

OUT = Path("/kaggle/working/t1_1_results")

recon.to_csv(
    OUT / "prediction_level_reconstruction.csv",
    index=False
)

pooled_prediction.to_csv(
    OUT / "pooled_flip_behavior_correlations.csv",
    index=False
)

within_prediction.to_csv(
    OUT / "within_rho_flip_behavior_correlations.csv",
    index=False
)

image_flip.to_csv(
    OUT / "image_level_flip_characterization.csv",
    index=False
)

print("\n" + "=" * 70)
print("CELL 10 COMPLETE")
print("=" * 70)

print("""
Prediction-level reconstruction is complete.

Do not make the final T1.1 conclusion yet.

The next decision will be whether the remaining endpoint
redundancy is:
  (1) mathematical,
  (2) a consequence of the shared rho dose-response,
  (3) a genuine cross-model mechanistic relationship, or
  (4) some combination of these.
""")

======================================================================
T1.1 — CELL 10: PREDICTION-LEVEL COUPLING AUDIT
======================================================================

Searching for final-checkpoint logit files...
Found 30 candidate __final.npz files

Evaluation labels:
  /kaggle/input/notebooks/tejasseshadriiiii/isic-kaggle-analysis/results/eval_y.npy
  N = 4713
  Positive = 1852
  Negative = 2861

Matched final-checkpoint logits: 30/30

======================================================================
PART A — RECONSTRUCTION AGAINST FROZEN ENDPOINTS
======================================================================
flip_fraction                       max_abs_error=8.327e-17
BA_clean                            max_abs_error=0.000e+00
BA_reversed                         max_abs_error=5.551e-17
BA_matched                          max_abs_error=1.110e-16
BA_neutral                          max_abs_error=0.000e+00
D                                   max_abs_error=9.714e-17
AUROC_clean                         max_abs_error=1.110e-16
AUROC_reversed                      max_abs_error=1.110e-16
AUROC_matched                       max_abs_error=2.220e-16
AUROC_neutral                       max_abs_error=1.110e-16
D_AUROC                             max_abs_error=3.053e-16
BA_neutral_minus_reversed           max_abs_error=8.327e-17

✓ All prediction-level quantities exactly reproduce
  the frozen endpoint table.

======================================================================
PART B — POOLED PREDICTION-LEVEL CORRELATIONS
======================================================================
                   target  pearson_r  pearson_p  spearman_r  spearman_p
                        D     0.9883     0.0000      0.9929      0.0000
                  D_AUROC     0.9967     0.0000      0.9933      0.0000
BA_neutral_minus_reversed     0.9976     0.0000      0.9924      0.0000

======================================================================
PART C — WITHIN-rho PREDICTION-LEVEL CORRELATIONS
======================================================================
   rho                    target  pearson_r  spearman_r  pearson_p  spearman_p
0.0000                         D     0.7299      0.6000     0.1615      0.2848
0.0000                   D_AUROC     0.9335      0.9000     0.0204      0.0374
0.0000 BA_neutral_minus_reversed     0.8061      0.6000     0.0995      0.2848
0.2000                         D     0.9778      1.0000     0.0040      0.0000
0.2000                   D_AUROC     0.8997      0.9000     0.0376      0.0374
0.2000 BA_neutral_minus_reversed     0.9800      1.0000     0.0034      0.0000
0.4000                         D     0.9266      0.8000     0.0236      0.1041
0.4000                   D_AUROC     0.8996      0.8000     0.0376      0.1041
0.4000 BA_neutral_minus_reversed     0.8394      0.9000     0.0754      0.0374
0.6000                         D     0.7012      0.7000     0.1870      0.1881
0.6000                   D_AUROC     0.2733      0.1000     0.6563      0.8729
0.6000 BA_neutral_minus_reversed     0.6693      0.5000     0.2166      0.3910
0.8000                         D     0.9430      0.4000     0.0162      0.5046
0.8000                   D_AUROC     0.7102      0.9000     0.1789      0.0374
0.8000 BA_neutral_minus_reversed     0.6289      0.8000     0.2557      0.1041
1.0000                         D     0.8300      0.9000     0.0820      0.0374
1.0000                   D_AUROC     0.8355      0.9000     0.0781      0.0374
1.0000 BA_neutral_minus_reversed     0.7756      0.5000     0.1232      0.3910

======================================================================
PART D — IMAGE-LEVEL FLIP CHARACTERIZATION
======================================================================
        model  n_flips  flip_fraction  benign_to_malignant_fraction  malignant_to_benign_fraction  fraction_flips_B_to_M  fraction_flips_M_to_B
rho_0.0_rep_1      352         0.0747                        0.0683                        0.0064                 0.9148                 0.0852
rho_0.0_rep_2      373         0.0791                        0.0721                        0.0070                 0.9115                 0.0885
rho_0.0_rep_3      391         0.0830                        0.0757                        0.0072                 0.9130                 0.0870
rho_0.0_rep_4      359         0.0762                        0.0685                        0.0076                 0.8997                 0.1003
rho_0.0_rep_5      306         0.0649                        0.0575                        0.0074                 0.8856                 0.1144
rho_0.2_rep_1     1020         0.2164                        0.2143                        0.0021                 0.9902                 0.0098
rho_0.2_rep_2     1123         0.2383                        0.2362                        0.0021                 0.9911                 0.0089
rho_0.2_rep_3      986         0.2092                        0.2073                        0.0019                 0.9909                 0.0091
rho_0.2_rep_4     1108         0.2351                        0.2328                        0.0023                 0.9901                 0.0099
rho_0.2_rep_5     1058         0.2245                        0.2232                        0.0013                 0.9943                 0.0057
rho_0.4_rep_1     1237         0.2625                        0.2625                        0.0000                 1.0000                 0.0000
rho_0.4_rep_2     1225         0.2599                        0.2597                        0.0002                 0.9992                 0.0008
rho_0.4_rep_3     1369         0.2905                        0.2896                        0.0008                 0.9971                 0.0029
rho_0.4_rep_4     1314         0.2788                        0.2786                        0.0002                 0.9992                 0.0008
rho_0.4_rep_5     1309         0.2777                        0.2775                        0.0002                 0.9992                 0.0008
rho_0.6_rep_1     1731         0.3673                        0.3671                        0.0002                 0.9994                 0.0006
rho_0.6_rep_2     1740         0.3692                        0.3690                        0.0002                 0.9994                 0.0006
rho_0.6_rep_3     1698         0.3603                        0.3601                        0.0002                 0.9994                 0.0006
rho_0.6_rep_4     1715         0.3639                        0.3637                        0.0002                 0.9994                 0.0006
rho_0.6_rep_5     1682         0.3569                        0.3567                        0.0002                 0.9994                 0.0006
rho_0.8_rep_1     2287         0.4853                        0.4853                        0.0000                 1.0000                 0.0000
rho_0.8_rep_2     2264         0.4804                        0.4804                        0.0000                 1.0000                 0.0000
rho_0.8_rep_3     2358         0.5003                        0.5003                        0.0000                 1.0000                 0.0000
rho_0.8_rep_4     2257         0.4789                        0.4789                        0.0000                 1.0000                 0.0000
rho_0.8_rep_5     2283         0.4844                        0.4844                        0.0000                 1.0000                 0.0000
rho_1.0_rep_1     2861         0.6070                        0.6070                        0.0000                 1.0000                 0.0000
rho_1.0_rep_2     2820         0.5983                        0.5981                        0.0002                 0.9996                 0.0004
rho_1.0_rep_3     2851         0.6049                        0.6049                        0.0000                 1.0000                 0.0000
rho_1.0_rep_4     2948         0.6255                        0.6255                        0.0000                 1.0000                 0.0000
rho_1.0_rep_5     2804         0.5950                        0.5947                        0.0002                 0.9996                 0.0004

======================================================================
CELL 10 COMPLETE
======================================================================

Prediction-level reconstruction is complete.

Do not make the final T1.1 conclusion yet.

The next decision will be whether the remaining endpoint
redundancy is:
  (1) mathematical,
  (2) a consequence of the shared rho dose-response,
  (3) a genuine cross-model mechanistic relationship, or
  (4) some combination of these.

In [11]:
# ======================================================================
# T1.1 — CELL 11: CLASS-CONDITIONAL PREDICTION-TRANSITION AUDIT
# ======================================================================

import numpy as np
import pandas as pd
from pathlib import Path
from scipy.stats import pearsonr, spearmanr

print("=" * 70)
print("T1.1 — CELL 11: CLASS-CONDITIONAL PREDICTION-TRANSITION AUDIT")
print("=" * 70)

# ----------------------------------------------------------------------
# 0. Paths
# ----------------------------------------------------------------------

CSV_PATH = Path(
    "/kaggle/input/notebooks/tejasseshadriiiii/"
    "isic-kaggle-analysis/results/"
    "model_endpoints_final_checkpoint.csv"
)

LOGIT_DIR_CANDIDATES = list(
    Path("/kaggle/input").rglob("*__final.npz")
)

df = pd.read_csv(CSV_PATH)

assert len(df) == 30
assert len(LOGIT_DIR_CANDIDATES) >= 30

# Evaluation labels
eval_candidates = list(
    Path("/kaggle/input").rglob("eval_y.npy")
)

assert eval_candidates

y = np.load(eval_candidates[0]).astype(int)

# Match logits
run_names = set(df["model"].astype(str))

logit_map = {}

for p in LOGIT_DIR_CANDIDATES:

    name = p.name.replace("__final.npz", "")

    if name in run_names:
        logit_map[name] = p

assert len(logit_map) == 30

# ----------------------------------------------------------------------
# 1. Helper
# ----------------------------------------------------------------------

def pred(z):
    return (z >= 0).astype(int)


def transition_stats(p_before, p_after, y):

    benign = (y == 0)
    malignant = (y == 1)

    B_to_M = (p_before == 0) & (p_after == 1)
    M_to_B = (p_before == 1) & (p_after == 0)

    return {

        # Overall
        "overall_B_to_M":
            float(B_to_M.mean()),

        "overall_M_to_B":
            float(M_to_B.mean()),

        "overall_flip":
            float((p_before != p_after).mean()),

        # Among truly benign images
        "benign_B_to_M":
            float(B_to_M[benign].mean()),

        "benign_M_to_B":
            float(M_to_B[benign].mean()),

        "benign_flip":
            float((p_before[benign] != p_after[benign]).mean()),

        # Among truly malignant images
        "malignant_B_to_M":
            float(B_to_M[malignant].mean()),

        "malignant_M_to_B":
            float(M_to_B[malignant].mean()),

        "malignant_flip":
            float((p_before[malignant] != p_after[malignant]).mean()),
    }


# ----------------------------------------------------------------------
# 2. Reconstruct transition statistics
# ----------------------------------------------------------------------

rows = []

for _, ref in df.iterrows():

    name = ref["model"]

    z = np.load(logit_map[name])

    p_clean = pred(z["z_clean"])
    p_hair = pred(z["z_hair"])
    p_reversed = pred(z["z_reversed"])

    assert len(p_clean) == len(y)

    clean_hair = transition_stats(
        p_clean,
        p_hair,
        y
    )

    clean_reversed = transition_stats(
        p_clean,
        p_reversed,
        y
    )

    row = {
        "model": name,
        "rho": ref["rho"],
        "replicate": ref["replicate"],
        "D_reference": ref["D"],
        "D_AUROC_reference": ref["D_AUROC"],
        "flip_fraction_reference": ref["flip_fraction"],
    }

    for k, v in clean_hair.items():
        row[f"hair_{k}"] = v

    for k, v in clean_reversed.items():
        row[f"reversed_{k}"] = v

    rows.append(row)

trans = pd.DataFrame(rows)

# ----------------------------------------------------------------------
# PART A — Clean → hair transition pattern
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART A — CLEAN → ALL-HAIR TRANSITIONS")
print("=" * 70)

cols = [
    "rho",
    "replicate",
    "hair_overall_B_to_M",
    "hair_overall_M_to_B",
    "hair_overall_flip",
    "hair_benign_B_to_M",
    "hair_malignant_M_to_B",
]

print(
    trans[cols]
    .sort_values(["rho", "replicate"])
    .to_string(
        index=False,
        float_format=lambda x: f"{x:.5f}"
    )
)

# ----------------------------------------------------------------------
# PART B — Clean → reversed transition pattern
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B — CLEAN → REVERSED TRANSITIONS")
print("=" * 70)

cols = [
    "rho",
    "replicate",
    "reversed_overall_B_to_M",
    "reversed_overall_M_to_B",
    "reversed_overall_flip",
    "reversed_benign_B_to_M",
    "reversed_malignant_M_to_B",
]

print(
    trans[cols]
    .sort_values(["rho", "replicate"])
    .to_string(
        index=False,
        float_format=lambda x: f"{x:.5f}"
    )
)

# ----------------------------------------------------------------------
# PART C — Exact balanced-accuracy transition decomposition
#
# BA = (Sensitivity + Specificity)/2
#
# For each ground-truth class:
#
# benign B→M increases false-positive rate
# malignant M→B decreases sensitivity
#
# Therefore:
#
# BA_clean - BA_reversed
#
# = 0.5 * [
#      (reversed benign B→M - clean benign B→M)
#      +
#      (clean malignant M→B - reversed malignant M→B)
#   ]
#
# We verify this directly.
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART C — EXACT BA DECOMPOSITION")
print("=" * 70)

trans["D_from_transitions"] = 0.5 * (
    (
        trans["reversed_benign_B_to_M"]
        -
        trans["hair_benign_B_to_M"]
    )
    +
    (
        trans["hair_malignant_M_to_B"]
        -
        trans["reversed_malignant_M_to_B"]
    )
)

# NOTE:
# The above compares clean->reversed against clean->hair.
# Therefore it is NOT the BA degradation itself.
#
# Instead reconstruct BA_clean and BA_reversed directly from
# their class-conditional error rates.

# Clean class error rates
# We can recover them from transitions relative to the prediction itself.

# Reconstruct exact BA difference directly from predictions.
D_exact_rows = []

for _, ref in df.iterrows():

    name = ref["model"]

    z = np.load(logit_map[name])

    p_clean = pred(z["z_clean"])
    p_reversed = pred(z["z_reversed"])

    benign = (y == 0)
    malignant = (y == 1)

    clean_FPR = (
        p_clean[benign] == 1
    ).mean()

    reversed_FPR = (
        p_reversed[benign] == 1
    ).mean()

    clean_FNR = (
        p_clean[malignant] == 0
    ).mean()

    reversed_FNR = (
        p_reversed[malignant] == 0
    ).mean()

    D_from_errors = 0.5 * (
        (reversed_FPR - clean_FPR)
        +
        (reversed_FNR - clean_FNR)
    )

    D_exact_rows.append({
        "model": name,
        "rho": ref["rho"],
        "replicate": ref["replicate"],
        "clean_FPR": clean_FPR,
        "reversed_FPR": reversed_FPR,
        "clean_FNR": clean_FNR,
        "reversed_FNR": reversed_FNR,
        "D_from_error_rates": D_from_errors,
        "D_reference": ref["D"],
    })

d_decomp = pd.DataFrame(D_exact_rows)

d_decomp["abs_error"] = np.abs(
    d_decomp["D_from_error_rates"]
    -
    d_decomp["D_reference"]
)

print(
    d_decomp[
        [
            "rho",
            "replicate",
            "clean_FPR",
            "reversed_FPR",
            "clean_FNR",
            "reversed_FNR",
            "D_from_error_rates",
            "D_reference",
            "abs_error",
        ]
    ].sort_values(
        ["rho", "replicate"]
    ).to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)

print(
    f"\nMaximum BA decomposition error: "
    f"{d_decomp['abs_error'].max():.3e}"
)

assert d_decomp["abs_error"].max() < 1e-10

# ----------------------------------------------------------------------
# PART D — What drives D?
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART D — COMPONENTS OF BEHAVIORAL HARM")
print("=" * 70)

d_decomp["delta_FPR"] = (
    d_decomp["reversed_FPR"]
    -
    d_decomp["clean_FPR"]
)

d_decomp["delta_FNR"] = (
    d_decomp["reversed_FNR"]
    -
    d_decomp["clean_FNR"]
)

d_decomp["FPR_contribution"] = (
    0.5 * d_decomp["delta_FPR"]
)

d_decomp["FNR_contribution"] = (
    0.5 * d_decomp["delta_FNR"]
)

print(
    d_decomp[
        [
            "rho",
            "replicate",
            "delta_FPR",
            "delta_FNR",
            "FPR_contribution",
            "FNR_contribution",
            "D_reference",
        ]
    ].sort_values(
        ["rho", "replicate"]
    ).to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)

# ----------------------------------------------------------------------
# PART E — Within-rho association with D
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART E — WITHIN-rho D COMPONENT CORRELATIONS")
print("=" * 70)

targets = [
    "delta_FPR",
    "delta_FNR",
    "FPR_contribution",
    "FNR_contribution",
]

for target in targets:

    print(f"\nD ↔ {target}")

    for rho in sorted(df["rho"].unique()):

        sub = d_decomp[
            d_decomp["rho"] == rho
        ]

        r_p, p_p = pearsonr(
            sub["D_reference"],
            sub[target]
        )

        r_s, p_s = spearmanr(
            sub["D_reference"],
            sub[target]
        )

        print(
            f"  rho={rho:.1f}: "
            f"Pearson={r_p:+.3f}, "
            f"Spearman={r_s:+.3f}"
        )

# ----------------------------------------------------------------------
# PART F — Summary by rho
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART F — MEAN BEHAVIORAL COMPONENTS BY rho")
print("=" * 70)

summary = (
    d_decomp
    .groupby("rho")
    [
        [
            "D_reference",
            "delta_FPR",
            "delta_FNR",
            "FPR_contribution",
            "FNR_contribution",
        ]
    ]
    .agg(["mean", "std"])
)

print(
    summary.to_string(
        float_format=lambda x: f"{x:.5f}"
    )
)

# ----------------------------------------------------------------------
# PART G — Save
# ----------------------------------------------------------------------

OUT = Path("/kaggle/working/t1_1_results")

trans.to_csv(
    OUT / "class_conditional_prediction_transitions.csv",
    index=False
)

d_decomp.to_csv(
    OUT / "D_error_rate_decomposition.csv",
    index=False
)

print("\n" + "=" * 70)
print("CELL 11 COMPLETE")
print("=" * 70)

print("""
The key question is now:

Does reversed-association harm arise predominantly through
an increase in false positives (benign → malignant),
false negatives (malignant → benign), or both?

Do not make the final T1.1 conclusion yet.
""")

======================================================================
T1.1 — CELL 11: CLASS-CONDITIONAL PREDICTION-TRANSITION AUDIT
======================================================================

======================================================================
PART A — CLEAN → ALL-HAIR TRANSITIONS
======================================================================
    rho  replicate  hair_overall_B_to_M  hair_overall_M_to_B  hair_overall_flip  hair_benign_B_to_M  hair_malignant_M_to_B
0.00000          1              0.06832              0.00637            0.07469             0.05557                0.00756
0.00000          2              0.07214              0.00700            0.07914             0.05557                0.00918
0.00000          3              0.07575              0.00721            0.08296             0.06396                0.00864
0.00000          4              0.06853              0.00764            0.07617             0.05662                0.01134
0.00000          5              0.05750              0.00743            0.06493             0.05208                0.01242
0.20000          1              0.21430              0.00212            0.21642             0.21706                0.00378
0.20000          2              0.23616              0.00212            0.23828             0.23453                0.00432
0.20000          3              0.20730              0.00191            0.20921             0.20657                0.00270
0.20000          4              0.23276              0.00233            0.23509             0.23418                0.00216
0.20000          5              0.22321              0.00127            0.22449             0.22405                0.00162
0.40000          1              0.26247              0.00000            0.26247             0.24642                0.00000
0.40000          2              0.25971              0.00021            0.25992             0.24956                0.00054
0.40000          3              0.28962              0.00085            0.29047             0.28137                0.00162
0.40000          4              0.27859              0.00021            0.27880             0.28137                0.00054
0.40000          5              0.27753              0.00021            0.27774             0.27298                0.00000
0.60000          1              0.36707              0.00021            0.36728             0.35687                0.00054
0.60000          2              0.36898              0.00021            0.36919             0.36980                0.00054
0.60000          3              0.36007              0.00021            0.36028             0.36561                0.00000
0.60000          4              0.36367              0.00021            0.36389             0.35687                0.00054
0.60000          5              0.35667              0.00021            0.35689             0.32821                0.00054
0.80000          1              0.48525              0.00000            0.48525             0.43307                0.00000
0.80000          2              0.48037              0.00000            0.48037             0.43761                0.00000
0.80000          3              0.50032              0.00000            0.50032             0.47780                0.00000
0.80000          4              0.47889              0.00000            0.47889             0.43691                0.00000
0.80000          5              0.48440              0.00000            0.48440             0.44390                0.00000
1.00000          1              0.60704              0.00000            0.60704             0.51520                0.00000
1.00000          2              0.59813              0.00021            0.59835             0.51171                0.00054
1.00000          3              0.60492              0.00000            0.60492             0.49039                0.00000
1.00000          4              0.62550              0.00000            0.62550             0.53233                0.00000
1.00000          5              0.59474              0.00021            0.59495             0.49144                0.00054

======================================================================
PART B — CLEAN → REVERSED TRANSITIONS
======================================================================
    rho  replicate  reversed_overall_B_to_M  reversed_overall_M_to_B  reversed_overall_flip  reversed_benign_B_to_M  reversed_malignant_M_to_B
0.00000          1                  0.02864                  0.00297                0.03161                 0.04719                    0.00000
0.00000          2                  0.02780                  0.00297                0.03077                 0.04579                    0.00000
0.00000          3                  0.03331                  0.00255                0.03586                 0.05488                    0.00000
0.00000          4                  0.02801                  0.00255                0.03055                 0.04614                    0.00000
0.00000          5                  0.02589                  0.00191                0.02780                 0.04264                    0.00000
0.20000          1                  0.10715                  0.00064                0.10779                 0.17651                    0.00000
0.20000          2                  0.11691                  0.00042                0.11734                 0.19259                    0.00000
0.20000          3                  0.10036                  0.00064                0.10100                 0.16533                    0.00000
0.20000          4                  0.11394                  0.00085                0.11479                 0.18770                    0.00000
0.20000          5                  0.11033                  0.00064                0.11097                 0.18175                    0.00000
0.40000          1                  0.11988                  0.00000                0.11988                 0.19748                    0.00000
0.40000          2                  0.12052                  0.00000                0.12052                 0.19853                    0.00000
0.40000          3                  0.13834                  0.00021                0.13855                 0.22789                    0.00000
0.40000          4                  0.13919                  0.00000                0.13919                 0.22929                    0.00000
0.40000          5                  0.13304                  0.00021                0.13325                 0.21915                    0.00000
0.60000          1                  0.17356                  0.00000                0.17356                 0.28591                    0.00000
0.60000          2                  0.18014                  0.00000                0.18014                 0.29675                    0.00000
0.60000          3                  0.17865                  0.00021                0.17887                 0.29430                    0.00000
0.60000          4                  0.17293                  0.00000                0.17293                 0.28487                    0.00000
0.60000          5                  0.15977                  0.00000                0.15977                 0.26319                    0.00000
0.80000          1                  0.21112                  0.00000                0.21112                 0.34778                    0.00000
0.80000          2                  0.21388                  0.00000                0.21388                 0.35232                    0.00000
0.80000          3                  0.23361                  0.00000                0.23361                 0.38483                    0.00000
0.80000          4                  0.21133                  0.00000                0.21133                 0.34813                    0.00000
0.80000          5                  0.21494                  0.00000                0.21494                 0.35407                    0.00000
1.00000          1                  0.25143                  0.00000                0.25143                 0.41419                    0.00000
1.00000          2                  0.24995                  0.00000                0.24995                 0.41174                    0.00000
1.00000          3                  0.24082                  0.00000                0.24082                 0.39671                    0.00000
1.00000          4                  0.26162                  0.00000                0.26162                 0.43097                    0.00000
1.00000          5                  0.24061                  0.00000                0.24061                 0.39636                    0.00000

======================================================================
PART C — EXACT BA DECOMPOSITION
======================================================================
     rho  replicate  clean_FPR  reversed_FPR  clean_FNR  reversed_FNR  D_from_error_rates  D_reference  abs_error
0.000000          1   0.115344      0.157637   0.307775      0.307775            0.021146     0.021146   0.000000
0.000000          2   0.110101      0.150996   0.318035      0.318035            0.020447     0.020447   0.000000
0.000000          3   0.122335      0.173016   0.286717      0.286717            0.025341     0.025341   0.000000
0.000000          4   0.106257      0.148200   0.314795      0.314795            0.020972     0.020972   0.000000
0.000000          5   0.106257      0.145753   0.284017      0.284017            0.019748     0.019748   0.000000
0.200000          1   0.087033      0.262496   0.344492      0.344492            0.087732     0.087732   0.000000
0.200000          2   0.091227      0.283118   0.368790      0.368790            0.095945     0.095945   0.000000
0.200000          3   0.082838      0.247116   0.355292      0.355292            0.082139     0.082139   0.000000
0.200000          4   0.091926      0.278224   0.352592      0.352592            0.093149     0.093149   0.000000
0.200000          5   0.084935      0.265641   0.359071      0.359071            0.090353     0.090353   0.000000
0.400000          1   0.056973      0.254456   0.431425      0.431425            0.098742     0.098742   0.000000
0.400000          2   0.061866      0.260398   0.405508      0.405508            0.099266     0.099266   0.000000
0.400000          3   0.063964      0.291506   0.419546      0.419546            0.113771     0.113771   0.000000
0.400000          4   0.068508      0.297798   0.394168      0.394168            0.114645     0.114645   0.000000
0.400000          5   0.069906      0.288710   0.406048      0.406048            0.109402     0.109402   0.000000
0.600000          1   0.051031      0.336945   0.480022      0.480022            0.142957     0.142957   0.000000
0.600000          2   0.048934      0.345683   0.456803      0.456803            0.148375     0.148375   0.000000
0.600000          3   0.057672      0.351625   0.440605      0.440605            0.146977     0.146977   0.000000
0.600000          4   0.053128      0.337994   0.455724      0.455724            0.142433     0.142433   0.000000
0.600000          5   0.039497      0.302691   0.509719      0.509719            0.131597     0.131597   0.000000
0.800000          1   0.015729      0.363509   0.652268      0.652268            0.173890     0.173890   0.000000
0.800000          2   0.021321      0.373646   0.628510      0.628510            0.176162     0.176162   0.000000
0.800000          3   0.022370      0.407200   0.600432      0.600432            0.192415     0.192415   0.000000
0.800000          4   0.024117      0.372247   0.619330      0.619330            0.174065     0.174065   0.000000
0.800000          5   0.024816      0.378889   0.622030      0.622030            0.177036     0.177036   0.000000
1.000000          1   0.006292      0.420482   0.803996      0.803996            0.207095     0.207095   0.000000
1.000000          2   0.009787      0.421531   0.780238      0.780238            0.205872     0.205872   0.000000
1.000000          3   0.004194      0.400909   0.849352      0.849352            0.198357     0.198357   0.000000
1.000000          4   0.005243      0.436211   0.818035      0.818035            0.215484     0.215484   0.000000
1.000000          5   0.005942      0.402307   0.813715      0.813715            0.198182     0.198182   0.000000

Maximum BA decomposition error: 1.943e-16

======================================================================
PART D — COMPONENTS OF BEHAVIORAL HARM
======================================================================
     rho  replicate  delta_FPR  delta_FNR  FPR_contribution  FNR_contribution  D_reference
0.000000          1   0.042293   0.000000          0.021146          0.000000     0.021146
0.000000          2   0.040895   0.000000          0.020447          0.000000     0.020447
0.000000          3   0.050682   0.000000          0.025341          0.000000     0.025341
0.000000          4   0.041943   0.000000          0.020972          0.000000     0.020972
0.000000          5   0.039497   0.000000          0.019748          0.000000     0.019748
0.200000          1   0.175463   0.000000          0.087732          0.000000     0.087732
0.200000          2   0.191891   0.000000          0.095945          0.000000     0.095945
0.200000          3   0.164278   0.000000          0.082139          0.000000     0.082139
0.200000          4   0.186298   0.000000          0.093149          0.000000     0.093149
0.200000          5   0.180706   0.000000          0.090353          0.000000     0.090353
0.400000          1   0.197483   0.000000          0.098742          0.000000     0.098742
0.400000          2   0.198532   0.000000          0.099266          0.000000     0.099266
0.400000          3   0.227543   0.000000          0.113771          0.000000     0.113771
0.400000          4   0.229290   0.000000          0.114645          0.000000     0.114645
0.400000          5   0.218805   0.000000          0.109402          0.000000     0.109402
0.600000          1   0.285914   0.000000          0.142957          0.000000     0.142957
0.600000          2   0.296749   0.000000          0.148375          0.000000     0.148375
0.600000          3   0.293953   0.000000          0.146977          0.000000     0.146977
0.600000          4   0.284865   0.000000          0.142433          0.000000     0.142433
0.600000          5   0.263195   0.000000          0.131597          0.000000     0.131597
0.800000          1   0.347780   0.000000          0.173890          0.000000     0.173890
0.800000          2   0.352324   0.000000          0.176162          0.000000     0.176162
0.800000          3   0.384830   0.000000          0.192415          0.000000     0.192415
0.800000          4   0.348130   0.000000          0.174065          0.000000     0.174065
0.800000          5   0.354072   0.000000          0.177036          0.000000     0.177036
1.000000          1   0.414191   0.000000          0.207095          0.000000     0.207095
1.000000          2   0.411744   0.000000          0.205872          0.000000     0.205872
1.000000          3   0.396714   0.000000          0.198357          0.000000     0.198357
1.000000          4   0.430968   0.000000          0.215484          0.000000     0.215484
1.000000          5   0.396365   0.000000          0.198182          0.000000     0.198182

======================================================================
PART E — WITHIN-rho D COMPONENT CORRELATIONS
======================================================================

D ↔ delta_FPR
  rho=0.0: Pearson=+1.000, Spearman=+1.000
  rho=0.2: Pearson=+1.000, Spearman=+1.000
  rho=0.4: Pearson=+1.000, Spearman=+1.000
  rho=0.6: Pearson=+1.000, Spearman=+1.000
  rho=0.8: Pearson=+1.000, Spearman=+1.000
  rho=1.0: Pearson=+1.000, Spearman=+1.000

D ↔ delta_FNR
  rho=0.0: Pearson=+nan, Spearman=+nan
  rho=0.2: Pearson=+nan, Spearman=+nan
  rho=0.4: Pearson=+nan, Spearman=+nan
  rho=0.6: Pearson=+nan, Spearman=+nan
  rho=0.8: Pearson=+nan, Spearman=+nan
  rho=1.0: Pearson=+nan, Spearman=+nan

D ↔ FPR_contribution
  rho=0.0: Pearson=+1.000, Spearman=+1.000
  rho=0.2: Pearson=+1.000, Spearman=+1.000
  rho=0.4: Pearson=+1.000, Spearman=+1.000
  rho=0.6: Pearson=+1.000, Spearman=+1.000
  rho=0.8: Pearson=+1.000, Spearman=+1.000
  rho=1.0: Pearson=+1.000, Spearman=+1.000

D ↔ FNR_contribution
  rho=0.0: Pearson=+nan, Spearman=+nan
  rho=0.2: Pearson=+nan, Spearman=+nan
  rho=0.4: Pearson=+nan, Spearman=+nan
  rho=0.6: Pearson=+nan, Spearman=+nan
  rho=0.8: Pearson=+nan, Spearman=+nan
  rho=1.0: Pearson=+nan, Spearman=+nan

======================================================================
PART F — MEAN BEHAVIORAL COMPONENTS BY rho
======================================================================
    D_reference         delta_FPR         delta_FNR         FPR_contribution         FNR_contribution
           mean     std      mean     std      mean     std             mean     std             mean     std
rho
0.0     0.02153 0.00220   0.04306 0.00440   0.00000 0.00000          0.02153 0.00220          0.00000 0.00000
0.2     0.08986 0.00530   0.17973 0.01059   0.00000 0.00000          0.08986 0.00530          0.00000 0.00000
0.4     0.10717 0.00771   0.21433 0.01543   0.00000 0.00000          0.10717 0.00771          0.00000 0.00000
0.6     0.14247 0.00659   0.28494 0.01318   0.00000 0.00000          0.14247 0.00659          0.00000 0.00000
0.8     0.17871 0.00778   0.35743 0.01555   0.00000 0.00000          0.17871 0.00778          0.00000 0.00000
1.0     0.20500 0.00717   0.41000 0.01434   0.00000 0.00000          0.20500 0.00717          0.00000 0.00000

======================================================================
CELL 11 COMPLETE
======================================================================

The key question is now:

Does reversed-association harm arise predominantly through
an increase in false positives (benign → malignant),
false negatives (malignant → benign), or both?

Do not make the final T1.1 conclusion yet.

/tmp/ipykernel_16/3155001796.py:417: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  r_p, p_p = pearsonr(
/tmp/ipykernel_16/3155001796.py:422: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  r_s, p_s = spearmanr(

In [12]:
# ======================================================================
# T1.1 — CELL 12: REDUNDANCY AUDIT SYNTHESIS / DECISION GATE
# ======================================================================

import numpy as np
import pandas as pd
from pathlib import Path

print("=" * 70)
print("T1.1 — CELL 12: REDUNDANCY AUDIT SYNTHESIS")
print("=" * 70)

# ----------------------------------------------------------------------
# 0. Load the audit outputs generated by Cells 1–11
# ----------------------------------------------------------------------

OUT = Path("/kaggle/working/t1_1_results")
OUT.mkdir(parents=True, exist_ok=True)

endpoint_csv = Path(
    "/kaggle/input/notebooks/tejasseshadriiiii/"
    "isic-kaggle-analysis/results/"
    "model_endpoints_final_checkpoint.csv"
)

df = pd.read_csv(endpoint_csv)

assert len(df) == 30

# ----------------------------------------------------------------------
# 1. Core PCA findings from Cell 7
# ----------------------------------------------------------------------

raw_pca = {
    "PC1_variance_fraction": 0.987581,
    "PCs_for_80pct": 1,
    "PCs_for_90pct": 1,
    "Kaiser_components": 1,
}

rho_adjusted_pca = {
    "PC1_variance_fraction": 0.563398,
    "PCs_for_80pct": 3,
    "PCs_for_90pct": 4,
    "Kaiser_components": 2,
}

# ----------------------------------------------------------------------
# 2. Core pooled redundancy findings
# ----------------------------------------------------------------------

pooled_spearman = {
    "delta_z_norm": 0.9849,
    "delta_p": 0.9840,
    "flip_fraction": 0.9782,
    "D": 0.9791,
    "D_AUROC": 0.9835,
    "BA_neutral_minus_reversed": 0.9720,
    "xai_enrichment": 0.9849,
}

# ----------------------------------------------------------------------
# 3. Near-rank-equivalence findings
# ----------------------------------------------------------------------

near_rank_pairs = {
    "delta_p__flip_fraction": 0.9973,
    "delta_p__D_AUROC": 0.9956,
    "flip_fraction__D_AUROC": 0.9933,
    "flip_fraction__D": 0.9929,
    "flip_fraction__BA_neutral_minus_reversed": 0.9924,
    "delta_z_norm__D_AUROC": 0.9915,
}

# ----------------------------------------------------------------------
# 4. Exact behavioral decomposition
# ----------------------------------------------------------------------

# Reconstruct directly from the endpoint table.
D = df["D"].to_numpy()

delta_FPR = (
    df["BA_reversed"] * 0.0
)

# The exact transition audit established:
# D = 0.5 * delta_FPR
# delta_FNR = 0
#
# Reconstruct delta_FPR from the underlying BA quantities:
#
# BA = (Sensitivity + Specificity)/2
#
# Specificity = 1 - FPR
#
# Therefore:
# D = 0.5 * [(FPR_reversed-FPR_clean)
#            +(FNR_reversed-FNR_clean)]
#
# Since delta_FNR = 0:
# delta_FPR = 2D

delta_FPR = 2.0 * D
delta_FNR = np.zeros_like(D)

decomposition_error = np.max(
    np.abs(
        D -
        0.5 * (delta_FPR + delta_FNR)
    )
)

assert decomposition_error < 1e-12

# ----------------------------------------------------------------------
# 5. Endpoint classification
# ----------------------------------------------------------------------

classification = pd.DataFrame([
    {
        "endpoint": "delta_z_hair",
        "role": "PRIMARY MECHANISTIC SIGNAL",
        "interpretation":
            "Continuous logit-level response to hair insertion; "
            "primary shortcut-reliance measure."
    },
    {
        "endpoint": "delta_z_norm",
        "role": "SCALE-NORMALIZED VERSION",
        "interpretation":
            "Normalized representation of the same logit perturbation."
    },
    {
        "endpoint": "delta_p",
        "role": "PROBABILITY-SCALE VERSION",
        "interpretation":
            "Probability-scale representation of the same clean→hair response."
    },
    {
        "endpoint": "flip_fraction",
        "role": "DISCRETE BEHAVIORAL TRANSFORMATION",
        "interpretation":
            "Decision-boundary manifestation of the clean→hair logit response."
    },
    {
        "endpoint": "D",
        "role": "PRIMARY DOWNSTREAM CONSEQUENCE",
        "interpretation":
            "Balanced-accuracy degradation under reversed association; "
            "in this dataset exactly equals 0.5 × FPR increase because "
            "FNR change is zero."
    },
    {
        "endpoint": "D_AUROC",
        "role": "RANK-BASED DOWNSTREAM CONSEQUENCE",
        "interpretation":
            "AUROC degradation; related to D but not algebraically identical."
    },
    {
        "endpoint": "BA_neutral_minus_reversed",
        "role": "ALGEBRAICALLY COUPLED BEHAVIORAL ENDPOINT",
        "interpretation":
            "Shares BA_reversed with D and is therefore not independent evidence."
    },
    {
        "endpoint": "xai_enrichment",
        "role": "INDEPENDENT AUXILIARY MECHANISTIC EVIDENCE",
        "interpretation":
            "Spatial attribution concentration in the hair region; "
            "requires the separate XAI sanity-check tier before strong claims."
    },
])

print("\n" + "=" * 70)
print("ENDPOINT ROLES")
print("=" * 70)

print(
    classification.to_string(
        index=False
    )
)

# ----------------------------------------------------------------------
# 6. Exact D decomposition summary
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("EXACT D DECOMPOSITION")
print("=" * 70)

print(
    f"Maximum reconstruction error: "
    f"{decomposition_error:.3e}"
)

print(
    f"Mean ΔFPR: {delta_FPR.mean():.6f}"
)

print(
    f"Mean ΔFNR: {delta_FNR.mean():.6f}"
)

print(
    f"Mean D: {D.mean():.6f}"
)

print(
    "\nTherefore, in this evaluation:"
)

print(
    "  D = 0.5 × ΔFPR"
)

print(
    "  ΔFNR = 0 for all 30 models"
)

# ----------------------------------------------------------------------
# 7. PCA summary
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("PCA EFFECTIVE DIMENSIONALITY")
print("=" * 70)

print(
    f"Raw endpoints:"
    f" PC1={raw_pca['PC1_variance_fraction']:.4f} "
    f"of variance; "
    f"{raw_pca['PCs_for_80pct']} PC for 80%; "
    f"{raw_pca['PCs_for_90pct']} PC for 90%"
)

print(
    f"rho-adjusted:"
    f" PC1={rho_adjusted_pca['PC1_variance_fraction']:.4f} "
    f"of variance; "
    f"{rho_adjusted_pca['PCs_for_80pct']} PCs for 80%; "
    f"{rho_adjusted_pca['PCs_for_90pct']} PCs for 90%"
)

# ----------------------------------------------------------------------
# 8. T1.1 decision statement
# ----------------------------------------------------------------------

decision = {
    "status": "COMPLETE",

    "pooled_redundancy":
        "HIGH",

    "raw_effective_dimension":
        "approximately 1",

    "rho_adjusted_effective_dimension":
        "approximately 3-4 components depending on criterion",

    "exact_algebraic_coupling":
        [
            "D = BA_clean - BA_reversed",
            "BA_neutral_minus_reversed = BA_neutral - BA_reversed",
            "D is exactly 0.5 × ΔFPR in the present evaluation",
            "ΔFNR = 0 for all 30 models",
        ],

    "mechanistic_interpretation":
        "The strongest behavioral consequence is a false-positive "
        "increase caused by benign→malignant prediction transitions "
        "under the reversed-association evaluation.",

    "independence_warning":
        "Raw pooled endpoint correlations must not be presented as "
        "independent convergent discoveries. Several endpoints are "
        "transformations or downstream manifestations of the same "
        "rho-dependent latent response.",

    "primary_reporting":
        [
            "delta_z_hair as primary mechanistic endpoint",
            "D as primary downstream behavioral consequence",
            "D_AUROC as complementary rank-based behavioral consequence",
            "xai_enrichment as auxiliary mechanistic evidence after validation",
        ],

    "do_not_count_as_independent":
        [
            "delta_z_norm",
            "delta_p",
            "flip_fraction",
            "BA_neutral_minus_reversed",
        ],
}

import json

with open(
    OUT / "T1_1_DECISION_SUMMARY.json",
    "w"
) as f:
    json.dump(
        decision,
        f,
        indent=2
    )

classification.to_csv(
    OUT / "T1_1_endpoint_roles.csv",
    index=False
)

print("\n" + "=" * 70)
print("T1.1 COMPLETE")
print("=" * 70)

print("""
Decision gate:

✓ Endpoint redundancy quantified
✓ Raw effective dimensionality quantified
✓ rho-adjusted dimensionality quantified
✓ Near-rank equivalence quantified
✓ Algebraic coupling identified
✓ Prediction-level mechanism audited
✓ Behavioral consequence decomposed

NEXT:
Proceed to T1.2 — DOSE-RESPONSE SHAPE AUDIT.

Do not fit a nonlinear curve yet.
First inspect the six rho-level means, within-rho
variation, and confidence intervals.
""")

======================================================================
T1.1 — CELL 12: REDUNDANCY AUDIT SYNTHESIS
======================================================================

======================================================================
ENDPOINT ROLES
======================================================================
                 endpoint                                       role                                                                                                                          interpretation
             delta_z_hair                 PRIMARY MECHANISTIC SIGNAL                                                   Continuous logit-level response to hair insertion; primary shortcut-reliance measure.
             delta_z_norm                   SCALE-NORMALIZED VERSION                                                                               Normalized representation of the same logit perturbation.
                  delta_p                  PROBABILITY-SCALE VERSION                                                                       Probability-scale representation of the same clean→hair response.
            flip_fraction         DISCRETE BEHAVIORAL TRANSFORMATION                                                                       Decision-boundary manifestation of the clean→hair logit response.
                        D             PRIMARY DOWNSTREAM CONSEQUENCE Balanced-accuracy degradation under reversed association; in this dataset exactly equals 0.5 × FPR increase because FNR change is zero.
                  D_AUROC          RANK-BASED DOWNSTREAM CONSEQUENCE                                                                        AUROC degradation; related to D but not algebraically identical.
BA_neutral_minus_reversed  ALGEBRAICALLY COUPLED BEHAVIORAL ENDPOINT                                                                    Shares BA_reversed with D and is therefore not independent evidence.
           xai_enrichment INDEPENDENT AUXILIARY MECHANISTIC EVIDENCE                 Spatial attribution concentration in the hair region; requires the separate XAI sanity-check tier before strong claims.

======================================================================
EXACT D DECOMPOSITION
======================================================================
Maximum reconstruction error: 0.000e+00
Mean ΔFPR: 0.248247
Mean ΔFNR: 0.000000
Mean D: 0.124123

Therefore, in this evaluation:
  D = 0.5 × ΔFPR
  ΔFNR = 0 for all 30 models

======================================================================
PCA EFFECTIVE DIMENSIONALITY
======================================================================
Raw endpoints: PC1=0.9876 of variance; 1 PC for 80%; 1 PC for 90%
rho-adjusted: PC1=0.5634 of variance; 3 PCs for 80%; 4 PCs for 90%

======================================================================
T1.1 COMPLETE
======================================================================

Decision gate:

✓ Endpoint redundancy quantified
✓ Raw effective dimensionality quantified
✓ rho-adjusted dimensionality quantified
✓ Near-rank equivalence quantified
✓ Algebraic coupling identified
✓ Prediction-level mechanism audited
✓ Behavioral consequence decomposed

NEXT:
Proceed to T1.2 — DOSE-RESPONSE SHAPE AUDIT.

Do not fit a nonlinear curve yet.
First inspect the six rho-level means, within-rho
variation, and confidence intervals.